### ISSUE TITLE
Panic with box shadow and the Qt backend

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#1010]
For example, viewing tests/cases/examples/box_shadow_use.slint with the Qt backend causes panic

```
thread 'main' panicked at 'already borrowed: BorrowMutError', ./internal/core/item_rendering.rs:45:35
stack backtrace:
[...]
   3: core::result::Result<T,E>::expect
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:975:23
   4: core::cell::RefCell<T>::borrow_mut
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/cell.rs:946:9
   5: i_slint_core::item_rendering::CachedRenderingData::get_or_update
             at ./internal/core/item_rendering.rs:45:29
   6: <i_slint_backend_qt::qt_window::QtItemRenderer as i_slint_core::item_rendering::ItemRenderer>::draw_box_shadow
             at ./internal/backends/qt/qt_window.rs:672:36
```

**Comment by tronical** [comment]
Ooops. What's around frame 7 and below?

**Comment by ogoffart** [comment]
I think it's my fault: b2caa757e73260971a6de4e2731b59958fde6fe8 add a  get_entry function, and it might not drop the borrowed cache soon enough

**Comment by tronical** [comment]
Ah yes, that makes sense. I recall running into the same issue :)

**Comment by ogoffart** [comment]
(too bad the rendering code is not tested in the CI)
