### ISSUE TITLE
This slint code panics during build

### ISSUE THREAD

**Issue by sztomi** [slint-ui/slint#1021]
```qml
MainWindow := Window {
  property <[Rectangle]> items;
  for entry[idx] in items : Rectangle { }
}
```

This produces a panic with the following backtrace:

```
❯ RUST_BACKTRACE=1 cargo b
   Compiling maple v0.1.0 (/home/tamas/projects/rust/slint_crash_repro/maple)
error: failed to run custom build command for `maple v0.1.0 (/home/tamas/projects/rust/slint_crash_repro/maple)`

Caused by:
  process didn't exit successfully: `/home/tamas/projects/rust/slint_crash_repro/maple/target/debug/build/maple-13f9fd8dc328c9d6/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/tamas/.cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-compiler-0.2.0/generator/rust.rs:502:62
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
     1: core::panicking::panic_fmt
               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
     2: core::panicking::panic
               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:50:5
     3: core::option::Option<T>::unwrap
               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/option.rs:746:21
     4: i_slint_compiler::generator::rust::generate_sub_component
               at /home/tamas/.cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-compiler-0.2.0/generator/rust.rs:502:38
     5: i_slint_compiler::generator::rust::generate_item_tree
               at /home/tamas/.cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-compiler-0.2.0/generator/rust.rs:845:20
     6: i_slint_compiler::generator::rust::generate_public_component
               at /home/tamas/.cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-compiler-0.2.0/generator/rust.rs:204:9
     7: i_slint_compiler::generator::rust::generate
               at /home/tamas/.cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-compiler-0.2.0/generator/rust.rs:123:17
     8: slint_build::compile_with_config
               at /home/tamas/.cargo/registry/src/github.com-1ecc6299db9ec823/slint-build-0.2.0/lib.rs:247:21
     9: slint_build::compile
               at /home/tamas/.cargo/registry/src/github.com-1ecc6299db9ec823/slint-build-0.2.0/lib.rs:180:5
    10: build_script_build::main
               at ./build.rs:2:3
    11: core::ops::function::FnOnce::call_once
               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
 ```

I don't know if this code is correct or not (I kind of expected it to be, based on the memory game tutorial). Regardless, it's probably a good idea to display a proper error and maybe a hint for the developer about a potential fix.

**Comment by ogoffart** [comment]
Thanks for the bug report.  A panic is indeed always a bug.

In this case the code is not correct because `Rectangle` is not a type that can be used in an array.
