### ISSUE TITLE
Live-Preview panics on Linux with CI built .vsix

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#2215]
The CI built nightly panics when trying to show a preview. This is the current back-trace:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: XError { description: "BadMatch (invalid parameter attributes)", error_code: 8, request_code: 131, minor_code: 3 }', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.28.1/src/platform_impl/linux/x11/window.rs:1131:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1791:5
   3: winit::platform_impl::platform::x11::window::UnownedWindow::inner_size_physical
   4: <i_slint_backend_winit::glwindow::GLWindow<Renderer> as i_slint_backend_winit::event_loop::WinitWindow>::draw
   5: i_slint_backend_winit::event_loop::CURRENT_WINDOW_TARGET::<impl i_slint_backend_winit::event_loop::CURRENT_WINDOW_TARGET>::set
   6: winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration
   7: <i_slint_backend_winit::Backend as i_slint_core::platform::Platform>::run_event_loop
   8: slint_lsp::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Info  - 2:01:24 PM] Connection to server got closed. Server will restart.
```

#2213 and commit e8439061e878f052afd23ed6ae27707901b65c83 were attempts at getter better diagnostics, but that just seems to have moved the panic now into winit.

So far I have not been able to reproduce this with a locally built preview lsp and .vsix :-(

**Comment by tronical** [comment]
Ok, after running `cargo update` locally I can reproduce this, with any program, not just the preview in vscode.

**Comment by tronical** [comment]
Ok, with glutin 0.30.3 it works, with 0.30.4 it panics.

**Comment by tronical** [comment]
Bisected to https://github.com/rust-windowing/glutin/pull/1548

**Comment by tronical** [comment]
With the glutin change we fail creating an EGL context and then fall back to GLX, but that fails on my X server later in winit then. We should really succeed with the EGL setup, like we did before, but that config is filtered out now.

**Comment by tronical** [comment]
Winit provides a window handle that always has 0 as visual_id (that's the unknown id).

**Comment by tronical** [comment]
Proposed glutin fix: https://github.com/rust-windowing/glutin/pull/1567
