### ISSUE TITLE
slint-ui Window crash when I minimized it

### ISSUE THREAD

**Issue by Max7Python** [slint-ui/slint#2259]
Im using the GUI and I get this msg error when running the application and I minimize the window, the app crash:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TryFromIntError(())', C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\i-slint-backend-winit-0.3.4\renderer\femtovg\glcontext.rs:46:40
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library\std\src\[panicking.rs:575](http://panicking.rs:575/)
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library\core\src\[panicking.rs:64](http://panicking.rs:64/)
   2: core::result::unwrap_failed
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library\core\src\[result.rs:1791](http://result.rs:1791/)
   3: enum2$<core::result::Result<core::num::nonzero::NonZeroU32,core::num::error::TryFromIntError> >::unwrap<core::num::nonzero::NonZeroU32,core::num::error::TryFromIntError>
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\core\src\[result.rs:1113](http://result.rs:1113/)
   4: i_slint_backend_winit::renderer::femtovg::glcontext::OpenGLContext::ensure_resized
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\i-slint-backend-winit-0.3.4\renderer\femtovg\[glcontext.rs:46](http://glcontext.rs:46/)
   5: i_slint_backend_winit::renderer::femtovg::impl$0::resize_event
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\i-slint-backend-winit-0.3.4\renderer\[femtovg.rs:245](http://femtovg.rs:245/)
   6: i_slint_backend_winit::glwindow::impl$1::resize_event<i_slint_backend_winit::renderer::femtovg::FemtoVGRenderer>
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\i-slint-backend-winit-0.3.4\[glwindow.rs:244](http://glwindow.rs:244/)
   7: i_slint_backend_winit::event_loop::process_window_event
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\i-slint-backend-winit-0.3.4\[event_loop.rs:242](http://event_loop.rs:242/)
   8: i_slint_backend_winit::event_loop::run::closure$1
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\i-slint-backend-winit-0.3.4\[event_loop.rs:450](http://event_loop.rs:450/)
   9: i_slint_backend_winit::event_loop::run::closure$2::closure$0
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\i-slint-backend-winit-0.3.4\[event_loop.rs:570](http://event_loop.rs:570/)
  10: i_slint_backend_winit::event_loop::CURRENT_WINDOW_TARGET::set<i_slint_backend_winit::event_loop::run::closure$2::closure_env$0,tuple$<> >
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\scoped-tls-hkt-0.1.2\src\[lib.rs:264](http://lib.rs:264/)
  11: i_slint_backend_winit::event_loop::run::closure$2
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\i-slint-backend-winit-0.3.4\[event_loop.rs:570](http://event_loop.rs:570/)
  12: winit::platform_impl::platform::event_loop::impl$3::run_return::closure$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent>,i_slint_backend_winit::event_loop::run::closure_env$2>
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\[event_loop.rs:254](http://event_loop.rs:254/)
  13: alloc::boxed::impl$46::call_mut<tuple$<enum2$<winit::event::Event<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >,ref_mut$<enum2$<winit::event_loop::ControlFlow> > >,dyn$<core::ops::function::FnMut<tuple$<enum2$<winit::event::Event<enum2$<i_sli
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\alloc\src\[boxed.rs:2016](http://boxed.rs:2016/)
  14: winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\[runner.rs:250](http://runner.rs:250/)
  15: core::panic::unwind_safe::impl$23::call_once<tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\core\src\panic\[unwind_safe.rs:271](http://unwind_safe.rs:271/)
  16: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >,tuple$<> >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\[panicking.rs:483](http://panicking.rs:483/)
  17: i_slint_backend_winit::glwindow::impl$1::resize_event::closure$0<i_slint_backend_winit::renderer::femtovg::FemtoVGRenderer>
  18: std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > > >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\[panicking.rs:447](http://panicking.rs:447/)
  19: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >,tuple$<> >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\[panic.rs:137](http://panic.rs:137/)
  20: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >::catch_unwind<enum2$<i_slint_backend_winit::event_loop::CustomEvent>,tuple$<>,winit::platform_impl::platform::event_loop::runner::
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\[runner.rs:157](http://runner.rs:157/)
  21: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >::call_event_handler<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\[runner.rs:242](http://runner.rs:242/)
  22: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >::send_event<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-027.5\src\platform_impl\windows\event_loop\[runner.rs:224](http://runner.rs:224/)
  23: winit::platform_impl::platform::event_loop::WindowData<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >::send_event<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-027.5\src\platform_impl\windows\[event_loop.rs:143](http://event_loop.rs:143/)

  24: winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\[event_loop.rs:1187](http://event_loop.rs:1187/)
  25: core::ops::function::FnOnce::call_once<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >,tuple$<> >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\core\src\ops\[function.rs:507](http://function.rs:507/)
  26: core::panic::unwind_safe::impl$23::call_once<isize,winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\core\src\panic\[unwind_safe.rs:271](http://unwind_safe.rs:271/)
  27: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >,isize>
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\[panicking.rs:483](http://panicking.rs:483/)
  28: i_slint_backend_winit::glwindow::impl$1::resize_event::closure$0<i_slint_backend_winit::renderer::femtovg::FemtoVGRenderer>
  29: std::panicking::try<isize,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > > >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\[panicking.rs:447](http://panicking.rs:447/)
  30: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >,isize>
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\[panic.rs:137](http://panic.rs:137/)
  31: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >::catch_unwind<enum2$<i_slint_backend_winit::event_loop::CustomEvent>,isize,winit::platform_impl::platform::event_loop::public_wind
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\[runner.rs:157](http://runner.rs:157/)
  32: winit::platform_impl::platform::event_loop::public_window_callback_inner<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\[event_loop.rs:2248](http://event_loop.rs:2248/)
  33: winit::platform_impl::platform::event_loop::public_window_callback<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\[event_loop.rs:939](http://event_loop.rs:939/)
  34: CallWindowProcW
  35: CallWindowProcW
  36: glPushClientAttrib
  37: CallWindowProcW
  38: DispatchMessageW
  39: SendMessageTimeoutW
  40: KiUserCallbackDispatcher
  41: NtUserMessageCall
  42: SendMessageW
  43: GetWindowTextW
  44: IsIconic
  45: IsCompositionActive
  46: IsCompositionActive
  47: GetWindowTextW
  48: winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\[event_loop.rs:1161](http://event_loop.rs:1161/)
  49: core::ops::function::FnOnce::call_once<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >,tuple$<> >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\core\src\ops\[function.rs:507](http://function.rs:507/)
  50: core::panic::unwind_safe::impl$23::call_once<isize,winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\core\src\panic\[unwind_safe.rs:271](http://unwind_safe.rs:271/)
  51: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >,isize>
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\[panicking.rs:483](http://panicking.rs:483/)
  52: i_slint_backend_winit::glwindow::impl$1::resize_event::closure$0<i_slint_backend_winit::renderer::femtovg::FemtoVGRenderer>
  53: std::panicking::try<isize,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > > >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\[panicking.rs:447](http://panicking.rs:447/)
  54: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >,isize>
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\[panic.rs:137](http://panic.rs:137/)
  55: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >::catch_unwind<enum2$<i_slint_backend_winit::event_loop::CustomEvent>,isize,winit::platform_impl::platform::event_loop::public_wind
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\[runner.rs:157](http://runner.rs:157/)
  56: winit::platform_impl::platform::event_loop::public_window_callback_inner<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\[event_loop.rs:2248](http://event_loop.rs:2248/)
  57: winit::platform_impl::platform::event_loop::public_window_callback<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\[event_loop.rs:939](http://event_loop.rs:939/)
  58: CallWindowProcW
  59: CallWindowProcW
  60: glPushClientAttrib
  61: CallWindowProcW
  62: DispatchMessageW
  63: LookupIconIdFromDirectoryEx
  64: KiUserCallbackDispatcher
  65: NtUserMessageCall
  66: GetWindowTextW
  67: IsIconic
  68: GetUserColorPreference
  69: Ordinal96
  70: IsCompositionActive
  71: IsCompositionActive
  72: GetWindowTextW
  73: winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\[event_loop.rs:1363](http://event_loop.rs:1363/)
  74: core::ops::function::FnOnce::call_once<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >,tuple$<> >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\core\src\ops\[function.rs:507](http://function.rs:507/)
  75: core::panic::unwind_safe::impl$23::call_once<isize,winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\core\src\panic\[unwind_safe.rs:271](http://unwind_safe.rs:271/)
  76: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >,isize>
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\[panicking.rs:483](http://panicking.rs:483/)
  77: i_slint_backend_winit::glwindow::impl$1::resize_event::closure$0<i_slint_backend_winit::renderer::femtovg::FemtoVGRenderer>
  78: std::panicking::try<isize,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > > >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\[panicking.rs:447](http://panicking.rs:447/)
  79: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >,isize>
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\[panic.rs:137](http://panic.rs:137/)
  80: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >::catch_unwind<enum2$<i_slint_backend_winit::event_loop::CustomEvent>,isize,winit::platform_impl::platform::event_loop::public_wind
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\[runner.rs:157](http://runner.rs:157/)
  81: winit::platform_impl::platform::event_loop::public_window_callback_inner<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\[event_loop.rs:2248](http://event_loop.rs:2248/)
  82: winit::platform_impl::platform::event_loop::public_window_callback<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\Gabriel\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\[event_loop.rs:939](http://event_loop.rs:939/)
  83: CallWindowProcW
  84: CallWindowProcW
  85: glPushClientAttrib
  86: CallWindowProcW
  87: DispatchMessageW
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\ventanas.exe` (exit code: 101)

any tips how to fix this?

Regards,
Max

**Comment by tronical** [comment]
Thanks for the report. This appears to happen only windows and we merged a fix yesterday with #2251 :)

**Comment by ogoffart** [comment]
Thanks again for the bug report.
As @tronical said, this has been fixed in master.  A workaround is to use the Qt backend.


By the way, unrelated question:  I see that you are using "slint-ui" in the title. Why did you call us like that instead of just "Slint"?  I'm asking because we've seen many user calling us like that, while we are branding ourselves as "Slint" and we are wondering if we should change something. Is it because of the GitHub account, or domain name?

**Comment by Max7Python** [comment]
Thanks for the answer, Im going to check it.
And with relation to use slint-ui and not Slint is because of "domain name", checking the website it say "Slint - The fast and easy UI Toolkit" and in the Rust code  "slint::slint!" Im going to use Slint from now 👍
