### ISSUE TITLE
GLXBadDrawable when trying to start live preview on vscode. EndeavourOS + i3wm

### ISSUE THREAD

**Issue by LJ3D** [slint-ui/slint#2288]
Error message from log:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { raw_code: Some(160), raw_os_message: Some("GLXBadDrawable"), kind: BadSurface }', internal/backends/winit/renderer/femtovg/glcontext.rs:172:75
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 17:53:40] Connection to server got closed. Server will restart.
[Error - 17:53:40] Request textDocument/codeLens failed.
Error: Connection got disposed.
    at Object.dispose (/home/lucian/.vscode/extensions/slint.slint-0.3.5/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
    at Object.dispose (/home/lucian/.vscode/extensions/slint.slint-0.3.5/node_modules/vscode-languageclient/lib/common/client.js:73:35)
    at LanguageClient.handleConnectionClosed (/home/lucian/.vscode/extensions/slint.slint-0.3.5/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
    at LanguageClient.handleConnectionClosed (/home/lucian/.vscode/extensions/slint.slint-0.3.5/node_modules/vscode-languageclient/lib/node/main.js:155:15)
    at closeHandler (/home/lucian/.vscode/extensions/slint.slint-0.3.5/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
    at CallbackList.invoke (/home/lucian/.vscode/extensions/slint.slint-0.3.5/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/home/lucian/.vscode/extensions/slint.slint-0.3.5/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at closeHandler (/home/lucian/.vscode/extensions/slint.slint-0.3.5/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
    at CallbackList.invoke (/home/lucian/.vscode/extensions/slint.slint-0.3.5/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/home/lucian/.vscode/extensions/slint.slint-0.3.5/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at StreamMessageReader.fireClose (/home/lucian/.vscode/extensions/slint.slint-0.3.5/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
    at Socket.<anonymous> (/home/lucian/.vscode/extensions/slint.slint-0.3.5/node_modules/vscode-jsonrpc/lib/common/messageReader.js:125:42)
    at Socket.emit (node:events:538:35)
    at Pipe.<anonymous> (node:net:687:12)
```

Some system info:
```
OS: EndeavourOS Linux x86_64 
Kernel: 6.1.12-arch1-1 
Resolution: 2560x1440 
WM: i3 
Theme: Arc-Dark [GTK2/3] 
Icons: Qogir [GTK2/3] 
Terminal: xfce4-terminal 
CPU: AMD Ryzen 5 2600 (12) @ 3.162GHz 
GPU: NVIDIA Quadro P5000 
```

**Comment by tronical** [comment]
I think that this is the same issue as #2269
