### ISSUE TITLE
interpreter panics on invalid expression when using callback aliases

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#2319]
The following test-case panics with `slint-viewer` when clicking into the touch area:

```slint
component TextInner inherits Text {
    callback panic();
    //init => { root.panic() }
    text: "Click me";
    TouchArea {
        clicked => { root.panic(); }
    }
}

component TextOuter {
    callback panic <=> inner.panic;
    inner := TextInner {
    }
}

export component Test inherits Window {
    width: 200px;
    height: 200px;
    TextOuter { 
    }
}
```

`thread 'main' panicked at 'invalid expression while evaluating', internal/interpreter/eval.rs:139:32`

When commeting in the `init` bit, it panics in the compiler:

`thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', internal/compiler/namedreference.rs:48:34`

This is also reproducible in the gallery:

`cargo run --bin slint-viewer -- ./examples/gallery/gallery.slint`, then go to the "controls" page and try to enter text in the line edit. The alias on the `edited` callback triggers the same bug.

**Comment by tronical** [comment]
Added to the 1.0.0 milestone because it's trivially triggered with the gallery.
