### ISSUE TITLE
PopupWindow causes unwrap on none (buildroot, arm cortex-a7 target)

### ISSUE THREAD

**Issue by flukejones** [slint-ui/slint#2799]
I'm having a hard time tracing this as I'm not familiar with the slint codebase. The issue does not occur unless Qt backend + eglfs is used. If run using winit-* and weston everything works as expected.

```
Fontconfig warning: "/usr/share/fontconfig/conf.avail/44-wqy-zenhei.conf", line 11: Having multiple values in <test> isn't supported and may not work as expected
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/luke/Projects/JTE/buildroot-external/buildroot/output/host/share/cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-core-1.0.2/window.rs:328:43
stack backtrace:
   0:   0xb0d574 - std::backtrace_rs::backtrace::libunwind::trace::h9326a7b179f3001c
                       at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:   0xb0d574 - std::backtrace_rs::backtrace::trace_unsynchronized::h2df72880374dbf84
                       at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:   0xb0d574 - std::sys_common::backtrace::_print_fmt::h8bd5852e67a215c6
                       at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:65:5
   3:   0xb0d574 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hecdecdaaf4c8d563
                       at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:44:22
   4:   0xb33530 - core::fmt::write::h8d662ff80d3092bd
                       at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/fmt/mod.rs:1213:17
   5:   0xb0a048 - std::io::Write::write_fmt::h1fdee927f151d1b3
                       at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/io/mod.rs:1682:15
   6:   0xb0d358 - std::sys_common::backtrace::_print::ha6df5e2840d6ccd9
                       at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:47:5
   7:   0xb0d358 - std::sys_common::backtrace::print::hd4f570bd95a6a759
                       at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:34:9
   8:   0xb0eb34 - std::panicking::default_hook::{{closure}}::h9b96f0d8cbce485a
                       at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:267:22
   9:   0xb0e808 - std::panicking::default_hook::hfcc6db4699ea7062
                       at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:286:9
  10:   0xb0f1e8 - std::panicking::rust_panic_with_hook::h2beb4d3d3ac49e4e
                       at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:688:13
  11:   0xb0ef9c - std::panicking::begin_panic_handler::{{closure}}::h44e6995b005a242e
                       at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:577:13
  12:   0xb0da98 - std::sys_common::backtrace::__rust_end_short_backtrace::h61ca6ecd192ef3d9
                       at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:137:18
  13:   0xb0ecf8 - rust_begin_unwind
                       at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
  14:   0x4fd370 - core::panicking::panic_fmt::h180ad7681e143349
                       at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
  15:   0x4fd40c - core::panicking::panic::he72abe5061b605dd
                       at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:114:5
  16:   0x85cd14 - core::option::Option<T>::unwrap::hb0e6404d65c0927b
                       at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/option.rs:823:21
  17:   0x85cd14 - i_slint_core::window::WindowInner::component::ha217a9287f91b907
                       at /home/luke/Projects/JTE/buildroot-external/buildroot/output/host/share/cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-core-1.0.2/window.rs:328:9
  18:   0x82fd44 - i_slint_core::window::WindowInner::draw_contents::{{closure}}::h8e647ed0c0a6637d
                       at /home/luke/Projects/JTE/buildroot-external/buildroot/output/host/share/cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-core-1.0.2/window.rs:621:32
  19:   0x82fd44 - i_slint_core::properties::CURRENT_BINDING::<impl i_slint_core::properties::CURRENT_BINDING>::set::hb9fad62c26b1fceb
                       at /home/luke/Projects/JTE/buildroot-external/buildroot/output/host/share/cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-hkt-0.1.2/src/lib.rs:264:25
  20:   0x830ba0 - i_slint_core::properties::PropertyTracker<DirtyHandler>::evaluate_as_dependency_root::h7745d8797884839c
                       at /home/luke/Projects/JTE/buildroot-external/buildroot/output/host/share/cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-core-1.0.2/properties.rs:1304:17
  21:   0x82e224 - i_slint_core::window::WindowInner::draw_contents::h5adf4981455f8fcb
                       at /home/luke/Projects/JTE/buildroot-external/buildroot/output/host/share/cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-core-1.0.2/window.rs:641:9
  22:   0x82e224 - i_slint_backend_qt::qt_window::QtWindow::paint_event::hde3764acd8f99fcf
                       at /home/luke/Projects/JTE/buildroot-external/buildroot/output/host/share/cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-backend-qt-1.0.2/qt_window.rs:1390:9
  23:   0x82e224 - i_slint_backend_qt::qt_window::Slint_paintEvent::{{closure}}::hb46cf7b781138d0f
                       at /home/luke/Projects/JTE/buildroot-external/buildroot/output/host/share/cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-backend-qt-1.0.2/qt_window.rs:99:17
  24:   0x82e224 - Slint_paintEvent
                       at /home/luke/Projects/JTE/buildroot-external/buildroot/output/host/share/cargo/registry/src/github.com-1ecc6299db9ec823/cpp-0.5.8/src/lib.rs:254:27
  25:   0x83a5e8 - _ZN11SlintWidget10paintEventEP11QPaintEvent
                       at /home/luke/Projects/JTE/buildroot-external/buildroot/output/host/share/cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-backend-qt-1.0.2/qt_window.rs:98:142
fatal runtime error: failed to initiate panic, error 9
Aborted
```

It occurs with a simply (all of) popup such as:
```
    popup := PopupWindow {
        x: root.width / 8;
        y: root.height / 8;
        height: (root.height / 8) * 6;
        width: (root.width / 8) * 6;

        // TODO: add properties to display
        Rectangle {
            height:100%;
            width: 100%;
            background: Theme.neutral-box;
            Text {text: counter;}
        }
    }

    TouchArea {
        height:100%; width: 100%;
        clicked => { popup.show(); }
    }
```

I'm unsure what other information might be required:

QT5 is built in buildroot with minimum:
![image](https://github.com/slint-ui/slint/assets/2015870/c6e84149-f858-441a-b3b5-bd5e62b7fdd3)

**Comment by tronical** [comment]
Thank you for the report and the detailed backtrace. I see that this can indeed happen if Qt sends an "early" paint event. We shouldn't panic here but just not paint anything. I'll look into it.

**Comment by tronical** [comment]
More specifically, I think in this qt eglfs situation Qt delivers a paint event maybe when calling show() right away, or something like that. Clearly before we've had a chance to call `set_component`.
