### ISSUE TITLE
Crash when executing simple example

### ISSUE THREAD

**Issue by terrarier2111** [slint-ui/slint#3069]
I am on fedora native and wanted to execute the simplest example in rust from the guide but instead of a nice window i got this nice crash:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/threadexception/.cargo/registry/src/index.crates.io-6f17d22bba15001f/accesskit_consumer-0.15.0/src/tree.rs:274:45
stack backtrace:
   0: rust_begin_unwind
             at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/85bf07972a1041b9e25393b803d0e006bec3eaaf/library/core/src/panicking.rs:117:5
   3: accesskit_consumer::tree::Tree::new
   4: accesskit_unix::adapter::Adapter::new
   5: alloc::rc::Rc<T>::new_cyclic
   6: i_slint_backend_winit::winitwindowadapter::WinitWindowAdapter::new
   7: i_slint_backend_winit::window_factory_fn
   8: <i_slint_backend_winit::Backend as i_slint_core::platform::Platform>::create_window_adapter
   9: slint::private_unstable_api::create_window_adapter
  10: once_cell::unsync::OnceCell<T>::get_or_try_init
  11: <RustSpeakClient::slint_generatedMainWindow::MainWindow as i_slint_core::api::ComponentHandle>::run
  12: tokio::runtime::park::CachedParkThread::block_on
  13: tokio::runtime::context::runtime::enter_runtime
  14: tokio::runtime::runtime::Runtime::block_on
  15: RustSpeakClient::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: queue 0x7f9014000ca0 destroyed while proxies still attached:
  zwp_primary_selection_device_v1@26 still attached
  zwp_primary_selection_device_manager_v1@22 still attached
  wl_data_device@25 still attached
  wl_seat@24 still attached
  wl_data_device_manager@23 still attached
  wl_registry@21 still attached
warning: queue 0x55f2f75fceb0 destroyed while proxies still attached:
  wl_buffer@53 still attached
  wl_buffer@52 still attached
  wl_buffer@30 still attached
  wl_buffer@51 still attached
  wl_subsurface@46 still attached
  wl_surface@45 still attached
  wl_subsurface@44 still attached
  wl_surface@43 still attached
  wl_subsurface@42 still attached
  wl_surface@41 still attached
  wl_subsurface@40 still attached
  wl_surface@39 still attached
  wl_subsurface@38 still attached
  wl_surface@37 still attached
  xdg_wm_base@35 still attached
  xdg_activation_v1@16 still attached
  zwp_text_input_manager_v3@15 still attached
  zwp_pointer_constraints_v1@14 still attached
  zwp_relative_pointer_manager_v1@13 still attached
  wl_seat@12 still attached
  wp_fractional_scale_manager_v1@11 still attached
  wp_viewporter@10 still attached
  wl_subcompositor@9 still attached
  wl_output@8 still attached
  wl_output@7 still attached
  wl_output@6 still attached
  wl_shm@5 still attached
  wl_compositor@4 still attached
  wl_registry@2 still attached

```

**Comment by ogoffart** [comment]
Thanks for reporting the bug.
This is the same as #3055  (see comments for workarounds)
We'll make a new release next week with a fix.
