### ISSUE TITLE
Use slint inside a devcontainer

### ISSUE THREAD

**Issue by BuriKizilkaya** [slint-ui/slint#3234]
Hi

Can I use slint inside your devcontainer. I was able to install dependencies and if execute the command `cargo run`, then the Window shows up. If I click on the "Show Preview" Button, then I get the following error:

```
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: XdgRuntimeDirNotSet X11 status: XOpenDisplayFailed', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/linux/mod.rs:757:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 8:58:09 PM] Connection to server got closed. Server will restart.
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
[Error - 8:58:09 PM] Request workspace/executeCommand failed.
Error: Connection got disposed.
    at Object.dispose (/home/vscode/.vscode-server/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
    at Object.dispose (/home/vscode/.vscode-server/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:73:35)
    at LanguageClient.handleConnectionClosed (/home/vscode/.vscode-server/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
    at LanguageClient.handleConnectionClosed (/home/vscode/.vscode-server/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/node/main.js:155:15)
    at closeHandler (/home/vscode/.vscode-server/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
    at CallbackList.invoke (/home/vscode/.vscode-server/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/home/vscode/.vscode-server/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at closeHandler (/home/vscode/.vscode-server/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
    at CallbackList.invoke (/home/vscode/.vscode-server/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/home/vscode/.vscode-server/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at StreamMessageReader.fireClose (/home/vscode/.vscode-server/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
    at Socket.<anonymous> (/home/vscode/.vscode-server/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageReader.js:125:42)
    at Socket.emit (node:events:525:35)
    at Pipe.<anonymous> (node:net:757:14)
```

The main issue is `Failed to initialize any backend!`.

**Comment by tronical** [comment]
Somehow the preview needs to be able to access our X server or wayland compositor, and it appears to be running inside the container. That means you may need to configure your devcontainer to forward for example the `DISPLAY` environment variable (for x11). How does your `devcontainer.json` look like? What's your host operating system?


I wonder if perhaps we should try to detect this (lack of availability of connection to display) and disable the "Show Preview" functionality. It's a little tricky to do just with winit, because that just panics (we don't get an error), but we could try to look for the corresponding variables yourselves to detect the lack of display.

**Comment by tronical** [comment]
(Tagging this as a bug, because either there's a way to make it work or we should try to detect and disable "Show Preview" IMO)
