### ISSUE TITLE
LSP: thread '<unnamed>' panicked at 'already borrowed: BorrowMutError'

### ISSUE THREAD

**Issue by bjorn** [slint-ui/slint#3468]
This happened on Linux (Fedora 38) using VS Code 1.82.1, while I was editing imports in a `.slint` file. I have Slint extension version 1.2.0 installed.

```
thread '<unnamed>' panicked at 'already borrowed: BorrowMutError', tools/lsp/main.rs:328:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 1:26:01 PM] Connection to server got closed. Server will restart.
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
thread '<unnamed>' panicked at 'already borrowed: BorrowMutError', tools/lsp/language.rs:253:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 1:26:01 PM] Connection to server got closed. Server will restart.
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
[Error - 1:26:01 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (/home/bjorn/.vscode/extensions/slint.slint-1.2.0/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
    at Object.dispose (/home/bjorn/.vscode/extensions/slint.slint-1.2.0/node_modules/vscode-languageclient/lib/common/client.js:73:35)
    at LanguageClient.handleConnectionClosed (/home/bjorn/.vscode/extensions/slint.slint-1.2.0/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
    at LanguageClient.handleConnectionClosed (/home/bjorn/.vscode/extensions/slint.slint-1.2.0/node_modules/vscode-languageclient/lib/node/main.js:155:15)
    at closeHandler (/home/bjorn/.vscode/extensions/slint.slint-1.2.0/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
    at CallbackList.invoke (/home/bjorn/.vscode/extensions/slint.slint-1.2.0/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/home/bjorn/.vscode/extensions/slint.slint-1.2.0/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at closeHandler (/home/bjorn/.vscode/extensions/slint.slint-1.2.0/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
    at CallbackList.invoke (/home/bjorn/.vscode/extensions/slint.slint-1.2.0/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/home/bjorn/.vscode/extensions/slint.slint-1.2.0/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at StreamMessageWriter.fireClose (/home/bjorn/.vscode/extensions/slint.slint-1.2.0/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
    at Socket.<anonymous> (/home/bjorn/.vscode/extensions/slint.slint-1.2.0/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12)
```

Issue looks similar to #2709.

I enabled `RUST_BACKTRACE=1` globally and managed to reproduce it:

```
thread '<unnamed>' panicked at 'already borrowed: BorrowMutError', tools/lsp/language.rs:319:54
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
   3: slint_lsp::language::RequestHandler::register::{{closure}}::{{closure}}
   4: slint_lsp::<impl slint_lsp::language::RequestHandler>::handle_request::{{closure}}
   5: slint_lsp::run_lsp_server
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Info  - 1:35:29 PM] Connection to server got closed. Server will restart.
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
[Error - 1:35:29 PM] Request textDocument/codeLens failed.
Error: Connection got disposed.
    ... (same JS backtrace as before)
```

### Steps to reproduce

I can reproduce it in my file, where I have the following import:
```js
import { Sources } from "./sources.slint";
```
When I place my cursor at the end of `sources`, and use Ctrl+backspace to delete the word, such that I get:
```js
import { Sources } from "./.slint";
```
Then the error occurs.

**Comment by tronical** [comment]
The multiply-borrowed variable seems to be `ctx.document_cache.borrow_mut()`. We have code like this:

```rust
 reload_document(
                &ctx,
                params.content_changes.pop().unwrap().text,
                params.text_document.uri,
                params.text_document.version,
                &mut ctx.document_cache.borrow_mut(),
            )
            .await?;
```

with this signature:

```rust
pub async fn reload_document(
    ctx: &Rc<Context>,
    content: String,
    uri: lsp_types::Url,
    version: i32,
    document_cache: &mut DocumentCache,
) -> Result<()>
```

That's asking for trouble indeed, the future is suspended while the RefCell is mutably borrowed.

I guess the function should rather take a `document_cache: &RefCell<DocumentCache>` instead and borrow mutably not across await boundaries.

**Comment by tronical** [comment]
This is a little tricky though, as eventually this calls `pub async fn load_file(&mut self, ...)`, where `&mut self` is the contents of the `RefCell`.

**Comment by ogoffart** [comment]
I can reproduce, when the preview is visible.

What's strange is that the local LSP should never actually await since the files should be loaded from disk

**Comment by tronical** [comment]
> I can reproduce, when the preview is visible.
> 
> What's strange is that the local LSP should never actually await since the files should be loaded from disk

Ahh indeed. Good fix!

The await scenario could still happen with an external document and the wasm build though, can't it?

**Comment by ogoffart** [comment]
In wasm build, there is a "mutex" in the wasm_main.rs so this cannot happen either

**Comment by tronical** [comment]
Great :)
