### ISSUE TITLE
Don't crash if xkb files aren't installed on the system

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#3678]
When xkb files are not present in the system, it seems an error message is printed along the lines of "xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb" and then the program crashes with "Segmentation fault". We should handle that gracefully in Slint.

**Comment by tronical** [comment]
Backtrace, for reference:

```
#0  0x00007ffff7f602f4 in xkb_context_ref () at /lib/x86_64-linux-gnu/libxkbcommon.so.0
#1  0x00007ffff7f72988 in  () at /lib/x86_64-linux-gnu/libxkbcommon.so.0
#2  0x00007ffff7f72a44 in xkb_keymap_new_from_names () at /lib/x86_64-linux-gnu/libxkbcommon.so.0
#3  0x000055555603a836 in xkbcommon::xkb::Keymap::new_from_names<str>
    (context=0x7fffffffd4d0, rules=..., model=..., layout=..., variant=..., options=..., flags=0)
    at /home/slint/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xkbcommon-0.6.0/src/xkb/mod.rs:667
#4  0x0000555556016fa1 in i_slint_backend_linuxkms::calloop_backend::input::LibInputHandler::init<i_slint_backend_linuxkms::calloop_backend::LoopData> (window=0x5555585ab720, event_loop_handle=0x7fffffffd840, seat=0x5555579179a0) at internal/backends/linuxkms/calloop_backend/input.rs:78
```

(after the error message in the description is printed)
