### ISSUE TITLE
Application aborts when running on WSL2

### ISSUE THREAD

**Issue by araraloren** [slint-ui/slint#4089]
Platform: `WSL2` `Fedora release 39 (Thirty Nine)` 
Slint: 1.3.2
```
Io error: Broken pipe (os error 32)
thread 'Io error: smithay-clipboard' panicked at /home/xxxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smithay-clipboard-0.7.0/src/worker.rs:98Broken pipe: (os error 4732:
)called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))

stack backtrace:
Io error: Broken pipe (os error 32)
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1652:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1077:23
   4: smithay_clipboard::worker::worker_impl
             at /home/xxxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smithay-clipboard-0.7.0/src/worker.rs:98:9
   5: smithay_clipboard::worker::spawn::{{closure}}
             at /home/xxxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smithay-clipboard-0.7.0/src/worker.rs:23:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Error: Other("Error running winit event loop: Exit Failure: 1")

 *  The terminal process "cargo 'run', '--package', 'slint-demo', '--bin', 'slint-demo'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.
```

```
fn main() -> Result<(), Box<dyn std::error::Error>> {
    MainWindow::new()?.run()?;
    Ok(())
}

slint::slint! {
    export component MainWindow inherits Window {
        Text {
            text: "Hello World!";
            color: red;
        }
    }
}
```
Running with `cargo run`, with default feature.

**Comment by araraloren** [comment]
@hunger Nothing. 
I try to debug it, I can see the window is display. But then it is crashed.

**Comment by araraloren** [comment]
Okay, I will try.

**Comment by araraloren** [comment]
@hunger It is working dependence configuration `slint = { version = "1.3", features = ["std", "backend-qt", "compat-1-2"], default-features = false}`.

**Comment by tronical** [comment]
The error message suggests that the peer that provides clipboard-data is not alive anymore (so the FD transfer fails). That's a little weird though. @araraloren did you do anything with your clipboard before launching? What happens if you select text in say a web browser or terminal, copy it into the clipboard, and then start the app?

**Comment by microhobby** [comment]
@tronical I have something similar:

```
  15:     0x7fac19414793 - core::panicking::panic_fmt::hd1e971d8d7c78e0e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
  16:     0x7fac19414c8a - core::result::unwrap_failed::hccb456d39e9c31fc
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
  17:     0x7fac1a805931 - core::result::Result<T,E>::unwrap::hfeb072dd70924711
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1077:23
  18:     0x7fac1945ff78 - slint_dotnet::rnet_export_run::inner::{{closure}}::h1a20187d20a525ea
                               at /home/castello/projects/D/slint-dotnet/src/lib.rs:546:9
  19:     0x7fac19462210 - std::thread::local::LocalKey<T>::try_with::h1a75201c014473e6
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/thread/local.rs:270:16
  20:     0x7fac194620ee - std::thread::local::LocalKey<T>::with::hfacaf4bd98b4a657
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/thread/local.rs:246:9
  21:     0x7fac1942c806 - slint_dotnet::rnet_export_run::inner::hfdf3cc9d37abdcad
                               at /home/castello/projects/D/slint-dotnet/src/lib.rs:537:5
  22:     0x7fac1942c7e6 - rnet_export_run
                               at /home/castello/projects/D/slint-dotnet/src/lib.rs:533:1
  23:     0x7fac1cdf6937 - <unknown>
fatal runtime error: failed to initiate panic, error 5
```

Even having stuff on the clipboard the error occurs.

**Comment by microhobby** [comment]
@tronical winit --example window:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/window`
DEBUG [sctk] Bound new global [11] wl_output v3
DEBUG [sctk] Bound new global [21] wl_output v3
DEBUG [sctk] Bound new global [4] zxdg_output_manager_v1 v2
DEBUG [sctk] Bound new global [19] wl_seat v7
DEBUG [sctk] supported wl_shm format Argb8888
DEBUG [sctk] supported wl_shm format Xrgb8888
DEBUG [sctk] supported wl_shm format Rgb565
TRACE [calloop::loop_logic] [calloop] Inserting new source #0
TRACE [calloop::loop_logic] [calloop] Inserting new source #1
TRACE [calloop::loop_logic] [calloop] Inserting new source #2
DEBUG [sctk_adwaita::buttons] Ignoring "appmenu" button
NewEvents(Init)
Resumed
WindowEvent { window_id: WindowId(WindowId(94398013310160)), event: RedrawRequested }
wl_shm_pool@24: error 1: invalid width, height or stride (0x44, 0)
Protocol error 1 on object wl_shm_pool@24:
thread 'main' panicked at examples/util/fill.rs:33:53:
Failed to create a softbuffer context: PlatformError(Some("Failed to make round trip to server"), Some(Backend(Protocol(ProtocolError { code: 1, object_id: 24, object_interface: "wl_shm_pool", message: "" }))))
stack backtrace:
   0:     0x55dabf92ae9c - std::backtrace_rs::backtrace::libunwind::trace::he43a6a3949163f8c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55dabf92ae9c - std::backtrace_rs::backtrace::trace_unsynchronized::h50db52ca99f692e7
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55dabf92ae9c - std::sys_common::backtrace::_print_fmt::hd37d595f2ceb2d3c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55dabf92ae9c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h678bbcf9da6d7d75
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55dabf95588c - core::fmt::rt::Argument::fmt::h3a159adc080a6fc9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
   5:     0x55dabf95588c - core::fmt::write::hb8eaf5a8e45a738e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
   6:     0x55dabf927c7e - std::io::Write::write_fmt::h9663fe36b2ee08f9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
   7:     0x55dabf92ac84 - std::sys_common::backtrace::_print::hcd4834796ee88ad2
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55dabf92ac84 - std::sys_common::backtrace::print::h1360e9450e4f922a
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55dabf92c243 - std::panicking::default_hook::{{closure}}::h2609fa95cd5ab1f4
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
  10:     0x55dabf92bf5c - std::panicking::default_hook::h6d75f5747cab6e8d
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
  11:     0x55dabf92c7c9 - std::panicking::rust_panic_with_hook::h57e78470c47c84de
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:707:13
  12:     0x55dabf92c6c7 - std::panicking::begin_panic_handler::{{closure}}::h3dfd2453cf356ecb
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:599:13
  13:     0x55dabf92b3c6 - std::sys_common::backtrace::__rust_end_short_backtrace::hdb177d43678e4d7e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x55dabf92c412 - rust_begin_unwind
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
  15:     0x55dabf2f8a13 - core::panicking::panic_fmt::hd1e971d8d7c78e0e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
  16:     0x55dabf2f8f0a - core::result::unwrap_failed::hccb456d39e9c31fc
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
  17:     0x55dabf362094 - core::result::Result<T,E>::expect::he9038bb3e28bb950
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1034:23
  18:     0x55dabf39c475 - window::fill::fill_window::GraphicsContext::new::h9f9a3206af3c9c0c
                               at /home/castello/tmp/winit/examples/util/fill.rs:33:26
  19:     0x55dabf384bfb - window::fill::fill_window::{{closure}}::{{closure}}::h0451db97bcb5657c
                               at /home/castello/tmp/winit/examples/util/fill.rs:66:36
  20:     0x55dabf3036b5 - core::option::Option<T>::get_or_insert_with::h24d4f0efe1ef198a
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/option.rs:1666:26
  21:     0x55dabf3849f1 - window::fill::fill_window::{{closure}}::hc2e6101b0210a983
                               at /home/castello/tmp/winit/examples/util/fill.rs:65:23
  22:     0x55dabf367627 - std::thread::local::LocalKey<T>::try_with::h9d19d49f2c8899a9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/thread/local.rs:270:16
  23:     0x55dabf367383 - std::thread::local::LocalKey<T>::with::hfef53c3e6b459148
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/thread/local.rs:246:9
  24:     0x55dabf39c41f - window::fill::fill_window::h6aa7cb0f17a8aea1
                               at /home/castello/tmp/winit/examples/util/fill.rs:55:5
  25:     0x55dabf39c970 - window::main::{{closure}}::h5a48d79487df167e
                               at /home/castello/tmp/winit/examples/window.rs:32:21
  26:     0x55dabf39c6af - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h9df81f3b97eb7984
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:294:13
  27:     0x55dabf37c1a8 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::single_iteration::h5fc5229cc4b23eef
                               at /home/castello/tmp/winit/src/platform_impl/linux/wayland/event_loop/mod.rs:504:17
  28:     0x55dabf379d49 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::pump_events::hf9788e9329075a4e
                               at /home/castello/tmp/winit/src/platform_impl/linux/wayland/event_loop/mod.rs:231:13
  29:     0x55dabf37a275 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_on_demand::h08b51621d5089d46
                               at /home/castello/tmp/winit/src/platform_impl/linux/wayland/event_loop/mod.rs:201:19
  30:     0x55dabf30739c - winit::platform_impl::platform::EventLoop<T>::run_on_demand::h3c954639b4ba2e1c
                               at /home/castello/tmp/winit/src/platform_impl/linux/mod.rs:828:56
  31:     0x55dabf307b06 - winit::platform_impl::platform::EventLoop<T>::run::h9243c09280c6b89a
                               at /home/castello/tmp/winit/src/platform_impl/linux/mod.rs:821:9
  32:     0x55dabf3956f7 - winit::event_loop::EventLoop<T>::run::hd747c19ef314e652
                               at /home/castello/tmp/winit/src/event_loop.rs:249:9
  33:     0x55dabf34248c - window::main::ha38252b990089dbc
                               at /home/castello/tmp/winit/examples/window.rs:23:5
  34:     0x55dabf368902 - core::ops::function::FnOnce::call_once::h768bff81eead98d0
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
  35:     0x55dabf33a99d - std::sys_common::backtrace::__rust_begin_short_backtrace::he51f960a866e548c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:154:18
  36:     0x55dabf394956 - std::rt::lang_start::{{closure}}::h4274860a571a8d93
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:166:18
  37:     0x55dabf9232db - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hbcc4f8a3f5ada78c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:284:13
  38:     0x55dabf9232db - std::panicking::try::do_call::he5f117a9e13dadde
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  39:     0x55dabf9232db - std::panicking::try::h2f3af9afce3a0443
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  40:     0x55dabf9232db - std::panic::catch_unwind::h6d6c387f38ef05ea
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  41:     0x55dabf9232db - std::rt::lang_start_internal::{{closure}}::h6ca09d5905711415
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:48
  42:     0x55dabf9232db - std::panicking::try::do_call::ha9fd18ea06654a4b
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  43:     0x55dabf9232db - std::panicking::try::hda5c2a4432362341
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  44:     0x55dabf9232db - std::panic::catch_unwind::h440f731b142bc235
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  45:     0x55dabf9232db - std::rt::lang_start_internal::hc0b4e50f058f62ce
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:20
  46:     0x55dabf39492a - std::rt::lang_start::h08e61a9fa1ae0e9a
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:165:17
  47:     0x55dabf34251e - main
  48:     0x7fe6b8088d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  49:     0x7fe6b8088e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  50:     0x55dabf2f9285 - _start
  51:                0x0 - <unknown>
```

**Comment by araraloren** [comment]
> The error message suggests that the peer that provides clipboard-data is not alive anymore (so the FD transfer fails). That's a little weird though. @araraloren did you do anything with your clipboard before launching? What happens if you select text in say a web browser or terminal, copy it into the clipboard, and then start the app?

Yes, it's working if I clean the clipboard from clipboard settings of Windows.

**Comment by microhobby** [comment]
> > The error message suggests that the peer that provides clipboard-data is not alive anymore (so the FD transfer fails). That's a little weird though. @araraloren did you do anything with your clipboard before launching? What happens if you select text in say a web browser or terminal, copy it into the clipboard, and then start the app?
> 
> Yes, it's working if I clean the clipboard from clipboard settings of Windows.

interesting, for me this does not work. Could you please share the Windows and WSL 2 version?

**Comment by araraloren** [comment]
@microhobby 
Here is the output of `wsl --version`(Fedora release 39 (Thirty Nine)):
```
WSL version： 2.0.9.0
Core version： 5.15.133.1-1
WSLg version： 1.0.59
MSRDC version： 1.2.4677
Direct3D version： 1.611.1-81528511
DXCore version： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version： 10.0.19045.3803
```

**Comment by ogoffart** [comment]
Upstream bug: https://github.com/Smithay/smithay-clipboard/issues/52

**Comment by ogoffart** [comment]
Closing as this is a bug upstream and we can't do anything in Slint

**Comment by tronical** [comment]
So this turned out not to be a bug in smithay-clipboard. It just happened to panic, but the root symptom is that the Wayland connection breaks off. Afaics Weston crashes. Have yet to find out why.

**Comment by tronical** [comment]
That's correct. It allows for better  error propagation, but what's crashing is Weston. I haven't figured out yet why. Perhaps I can file a ticket with wslg - Weston should not crash. The clipboard is a red herring.

As to workaround: I don't know any yet :(.

**Comment by microhobby** [comment]
I think that I figure out a workaround:

```bash
WAYLAND_DISPLAY= slint_app
```

Unsetting the `WAYLAND_DISPLAY` appears to fix the panic. The point against it is that it will use the X11 as a fallback.

**Comment by tronical** [comment]
This is worked around now with https://github.com/slint-ui/slint/issues/5657 until we have https://github.com/slint-ui/slint/issues/5667 in place.
