### ISSUE TITLE
crashes when resizing opengl_texture example

### ISSUE THREAD

**Issue by qarmin** [slint-ui/slint#4195]
Slint 1.3.2

Short panic
```
thread 'main' panicked at examples/opengl_texture/main.rs:119:9:
assertion `left == right` failed
  left: 36054
 right: 36053
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```
command `cargo run`

full backtrace
```
stack backtrace:
   0:     0x55cabfbc2f5c - std::backtrace_rs::backtrace::libunwind::trace::ha69d38c49f1bf263
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55cabfbc2f5c - std::backtrace_rs::backtrace::trace_unsynchronized::h93125d0b85fd543c
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55cabfbc2f5c - std::sys_common::backtrace::_print_fmt::h8d65f438e8343444
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55cabfbc2f5c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41751d2af6c8033a
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55cabfbf306c - core::fmt::rt::Argument::fmt::h5db2f552d8a28f63
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/fmt/rt.rs:138:9
   5:     0x55cabfbf306c - core::fmt::write::h99465148a27e4883
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/fmt/mod.rs:1114:21
   6:     0x55cabfbbe2fe - std::io::Write::write_fmt::hee8dfd57bd179ab2
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/io/mod.rs:1763:15
   7:     0x55cabfbc2d44 - std::sys_common::backtrace::_print::h019a3cee3e814da4
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55cabfbc2d44 - std::sys_common::backtrace::print::h55694121c2ddf918
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55cabfbc4233 - std::panicking::default_hook::{{closure}}::h29cbe3da3891b0b0
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:272:22
  10:     0x55cabfbc3f54 - std::panicking::default_hook::h881e76b2b8c74280
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:292:9
  11:     0x55cabfbc47d5 - std::panicking::rust_panic_with_hook::hcc36e25b6e33969c
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:731:13
  12:     0x55cabfbc46d1 - std::panicking::begin_panic_handler::{{closure}}::ha415efb0f69f41f9
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:609:13
  13:     0x55cabfbc3486 - std::sys_common::backtrace::__rust_end_short_backtrace::h395fe90f99451e4e
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x55cabfbc4422 - rust_begin_unwind
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
  15:     0x55cabfbf0555 - core::panicking::panic_fmt::h452a83e54ecd764e
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
  16:     0x55cabfbf09ab - core::panicking::assert_failed_inner::h878b898cfe1c2eaf
  17:     0x55cabfb32dfe - core::panicking::assert_failed::h5f9511ebf521eb7d
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:270:5
  18:     0x55cabea726af - opengl_texture::DemoTexture::new::h74ea9c71c2180ee3
                               at /home/rafal/test/slint/examples/opengl_texture/main.rs:119:9
  19:     0x55cabea732fc - opengl_texture::DemoRenderer::render::h0f815037d0ff5c20
                               at /home/rafal/test/slint/examples/opengl_texture/main.rs:354:39
  20:     0x55cabea4212e - opengl_texture::main::{{closure}}::h50bd0fdc7fdee7d3
                               at /home/rafal/test/slint/examples/opengl_texture/main.rs:422:35
Aborted (core dumped)

```

https://github.com/slint-ui/slint/assets/41945903/bfea8e90-301e-47bb-bc63-bb1282643469

**Comment by qarmin** [comment]
Well, this happens really randomly - sometimes at start, but always when resizing to 0 width/height.


https://github.com/slint-ui/slint/assets/41945903/bdd54cf2-f3d7-4a91-9524-f5c062eba0b6
