### ISSUE TITLE
VScode slint extention failed

### ISSUE THREAD

**Issue by kaarelen** [slint-ui/slint#4475]
os: rolling, arch
env: vscode 1.85.2 with nightly slint extentions

I've just messed around with TouchArea props with opened live preview. (i know that it takes not a bool)
```
tmp := TouchArea {
    forward-focus: true;
}
```

```
thread 'LanguageServer' panicked at internal/compiler/passes/focus_handling.rs:95:17:
internal error: forward-focus property is of type ElementReference but received non-element-reference binding
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 1:33:00 AM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
thread 'LanguageServer' panicked at internal/compiler/passes/focus_handling.rs:95:17:
internal error: forward-focus property is of type ElementReference but received non-element-reference binding
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 1:33:00 AM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
thread 'LanguageServer' panicked at internal/compiler/passes/focus_handling.rs:95:17:
internal error: forward-focus property is of type ElementReference but received non-element-reference binding
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 1:33:01 AM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
thread 'LanguageServer' panicked at internal/compiler/passes/focus_handling.rs:95:17:
internal error: forward-focus property is of type ElementReference but received non-element-reference binding
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 1:33:01 AM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
thread 'LanguageServer' panicked at internal/compiler/passes/focus_handling.rs:95:17:
internal error: forward-focus property is of type ElementReference but received non-element-reference binding
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Error - 1:33:01 AM] The Slint LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
```

**Comment by ogoffart** [comment]
I can reproduce with this simple test case:

```
export component MainWindow inherits Window {
    TouchArea {
        forward-focus: true;
    }
}
```
