### ISSUE TITLE
Panic when running demo on WSL2 (XKBNotFound)

### ISSUE THREAD

**Issue by noahetka** [slint-ui/slint#4610]
Platform: WSL2 Ubuntu 22.04.3 LTS
Slint: 1.4.1

I'm trying to follow the tutorial and anytime I use anything slint related it crashes.

```
`target/debug/memory`
thread 'main' panicked at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform_impl/linux/wayland/seat/keyboard/mod.rs:292:40:
called `Result::unwrap()` on an `Err` value: XKBNotFound
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1073:23
   4: winit::platform_impl::platform::wayland::seat::keyboard::KeyboardState::new
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform_impl/linux/wayland/seat/keyboard/mod.rs:292:24
   5: winit::platform_impl::platform::wayland::seat::<impl smithay_client_toolkit::seat::SeatHandler for winit::platform_impl::platform::wayland::state::WinitState>::new_capability
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform_impl/linux/wayland/seat/mod.rs:86:26
   6: <smithay_client_toolkit::seat::SeatState as wayland_client::event_queue::Dispatch<wayland_client::protocol::wl_seat::WlSeat,smithay_client_toolkit::seat::SeatData,D>>::event
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smithay-client-toolkit-0.18.1/src/seat/mod.rs:465:33
   7: winit::platform_impl::platform::wayland::seat::<impl wayland_client::event_queue::Dispatch<wayland_client::protocol::wl_seat::WlSeat,smithay_client_toolkit::seat::SeatData> for winit::platform_impl::platform::wayland::state::WinitState>::event
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-client-0.31.2/src/event_queue.rs:798:17
   8: wayland_client::event_queue::queue_callback
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-client-0.31.2/src/event_queue.rs:656:5
   9: wayland_client::event_queue::EventQueue<State>::dispatching_impl
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-client-0.31.2/src/event_queue.rs:478:13
  10: wayland_client::event_queue::EventQueue<State>::dispatch_pending
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-client-0.31.2/src/event_queue.rs:384:9
  11: wayland_client::event_queue::EventQueue<State>::blocking_dispatch
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-client-0.31.2/src/event_queue.rs:406:9
  12: wayland_client::event_queue::EventQueue<State>::roundtrip
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-client-0.31.2/src/event_queue.rs:431:27
  13: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform_impl/linux/wayland/event_loop/mod.rs:100:13
  14: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform_impl/linux/mod.rs:793:9
  15: winit::platform_impl::platform::EventLoop<T>::new
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform_impl/linux/mod.rs:785:33
  16: winit::event_loop::EventLoopBuilder<T>::build
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/event_loop.rs:128:25
  17: i_slint_backend_winit::event_loop::NotRunningEventLoop::new
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-backend-winit-1.4.1/event_loop.rs:59:13
  18: i_slint_backend_winit::event_loop::with_window_target::{{closure}}
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-backend-winit-1.4.1/event_loop.rs:195:52
  19: std::thread::local::LocalKey<T>::try_with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:270:16
  20: std::thread::local::LocalKey<T>::with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:246:9
  21: i_slint_backend_winit::event_loop::with_window_target
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-backend-winit-1.4.1/event_loop.rs:193:9
  22: i_slint_backend_winit::Backend::new_with_renderer_by_name
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-backend-winit-1.4.1/lib.rs:173:9
  23: i_slint_backend_winit::Backend::new
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-backend-winit-1.4.1/lib.rs:165:9
  24: i_slint_backend_selector::create_winit_backend
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-backend-selector-1.4.1/lib.rs:29:17
  25: i_slint_backend_selector::create_default_backend
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-backend-selector-1.4.1/lib.rs:72:23
  26: i_slint_backend_selector::create_backend
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-backend-selector-1.4.1/lib.rs:115:13
  27: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  28: i_slint_core::context::with_platform::{{closure}}
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-core-1.4.1/context.rs:63:43
  29: std::thread::local::LocalKey<T>::try_with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:270:16
  30: std::thread::local::LocalKey<T>::with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:246:9
  31: i_slint_core::context::with_platform
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-core-1.4.1/context.rs:60:5
  32: i_slint_backend_selector::with_platform
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-backend-selector-1.4.1/lib.rs:136:5
  33: slint::private_unstable_api::ensure_backend
             at /home/zoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/slint-1.4.1/private_unstable_api.rs:140:5
  34: memory::slint_generatedMainWindow::InnerMainWindow::new
             at ./src/main.rs:7:1
  35: memory::slint_generatedMainWindow::MainWindow::new
             at ./src/main.rs:7:1
  36: memory::main
             at ./src/main.rs:4:5
  37: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace. 
```

```
use std::env;
fn main() {
    env::set_var("RUST_BACKTRACE", "1");
    MainWindow::new().unwrap().run().unwrap();
}

slint::slint! {
    export component MainWindow inherits Window {
        Text {
            text: "hello world";
            color: green;
        }
    }
}
```
Running with cargo run, with default feature. Very new to all this. Thanks for any help I've been trying to solve this for days.

**Comment by noahetka** [comment]
Solution stumbled upon

Ran the following from [WSLG repo](https://github.com/microsoft/wslg)
```
## Gedit
sudo apt install gedit -y

## GIMP
sudo apt install gimp -y

## Nautilus
sudo apt install nautilus -y

## VLC
sudo apt install vlc -y

## X11 apps
sudo apt install x11-apps -y
```
I dont think this was the solution, but just documenting changes. After this I ran 
```
sudo apt install 

sudo apt-get dist-upgrade
```
and found some upgrades, and then it all worked!

Sorry if this was the wrong place for all this- very new here. Can remove if needed.
