### ISSUE TITLE
Server crashes when trying to show live preview. VS Code

### ISSUE THREAD

**Issue by jasper-at-windswept** [slint-ui/slint#4619]
I was originally having troubles in issue #3412 but resolved it by setting up Nix-ld.

However now when i press the Show Preview code lense the slint server crashes.

```
Using Skia Software renderer
Rendering at 1920x1080
thread 'main' panicked at tools/lsp/preview/native.rs:83:40:
called `Result::unwrap()` on an `Err` value: OtherError("Error presenting fb: permission denied")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 9:52:00 AM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug.
```

**Comment by jasper-at-windswept** [comment]
Ldd outputs the below:
```
ldd slint-lsp-x86_64-unknown-linux-gnu

	linux-vdso.so.1 (0x00007ffcc15f5000)
	libxkbcommon.so.0 => not found
	libudev.so.1 => not found
	libinput.so.10 => not found
	libgbm.so.1 => not found
	libstdc++.so.6 => not found
	libfontconfig.so.1 => not found
	libfreetype.so.6 => not found
	libdl.so.2 => /nix/store/cyrrf49i2hm1w7vn2j945ic3rrzgxbqs-glibc-2.38-44/lib/libdl.so.2 (0x00007ff60e03c000)
	libgcc_s.so.1 => /nix/store/f5my15qww10swmf66ns13l24yp6j5dmq-xgcc-13.2.0-libgcc/lib/libgcc_s.so.1 (0x00007ff60e017000)
	libpthread.so.0 => /nix/store/cyrrf49i2hm1w7vn2j945ic3rrzgxbqs-glibc-2.38-44/lib/libpthread.so.0 (0x00007ff60e012000)
	libm.so.6 => /nix/store/cyrrf49i2hm1w7vn2j945ic3rrzgxbqs-glibc-2.38-44/lib/libm.so.6 (0x00007ff60df2e000)
	libc.so.6 => /nix/store/cyrrf49i2hm1w7vn2j945ic3rrzgxbqs-glibc-2.38-44/lib/libc.so.6 (0x00007ff60bc17000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/cyrrf49i2hm1w7vn2j945ic3rrzgxbqs-glibc-2.38-44/lib64/ld-linux-x86-64.so.2 (0x00007ff60e045000)
```

What does not make sense is i have all those not found dependencies outlined in `nix-ld` and i can use `sudo find` and locate all those .so files

**Comment by ogoffart** [comment]
Thanks for reporting the problem

We have two problem:
 1. the lsp is panicking because we unwrap the error from slint::run_event_loop instead of properly reporting it as an error and maybe use a fallback. This is tracked in https://github.com/slint-ui/slint/issues/204

 2. You have a problem that you can't connect to the display. This error comes from the linuxkms backend. The linuxkms is used because the winit backend failled to initialize, probably because the X11 DISPLAY or equivalent wayland env variable were not properly set. And you probably don't want anyway that linuxkms backend takes your whole screen

Since the LSP Preview bug is already tracked by #204,  the actual problem seems to be a configuration problem. 

I'm just going to keep this bug open because I think the linuxkms error is less than ideal.
 - It should ideally error out before, while creating the backend, so that the backend selector can fallback or display all the backend's errors. I don't know it that's possible thougyh
 - It should tell more info than just "Error presenting fb: permission denied".  Permission denied to what? What is it even trying to do.

**Comment by bemyak** [comment]
I'm having the same issue on NixOS. In my environment, all dependencies seem to be satisfied:
```bash
$ ldd /home/bemyak/.vscode-oss/extensions/slint.slint-nightly-2024.9.1017/bin/slint-lsp-x86_64-unknown-linux-gnu                                                                                                                                 
        linux-vdso.so.1 (0x000072bcf387b000)
        libxkbcommon.so.0 => /nix/store/rnlflxkgglrdiii7wl7k99893zr4iamc-libxkbcommon-1.7.0/lib/libxkbcommon.so.0 (0x000072bcf382a000)
        libudev.so.1 => /nix/store/p7j28d8lajpgvmpxgjljj2kkm9lzzq6l-eudev-3.2.14/lib/libudev.so.1 (0x000072bcf3800000)
        libinput.so.10 => /nix/store/4h5k8gvvx52cwm1hlqvlaj6k6gmnqllb-libinput-1.26.1/lib/libinput.so.10 (0x000072bcf37a5000)
        libgbm.so.1 => /nix/store/hykhzxanlm463wpcw2546rp9ba8hjcz6-mesa-24.2.1/lib/libgbm.so.1 (0x000072bcf3794000)
        libstdc++.so.6 => /nix/store/zx9zgvy2nsxcmpn0fzx277m5lk352cdf-gcc-13.3.0-lib/lib/libstdc++.so.6 (0x000072bcf1200000)
        libfontconfig.so.1 => /nix/store/yvzgpzlqyabi6rkciqpl5lgaml30c1as-fontconfig-2.15.0-lib/lib/libfontconfig.so.1 (0x000072bcf15b2000)
        libfreetype.so.6 => /nix/store/6drdmi571fj4c09j4ryaij0apg92wcn4-freetype-2.13.2/lib/libfreetype.so.6 (0x000072bcf14e0000)
        libdl.so.2 => /nix/store/wlffq5p6mxxgfap10sav3ij936jzqm59-glibc-2.39-52/lib/libdl.so.2 (0x000072bcf378d000)
        libgcc_s.so.1 => /nix/store/zx9zgvy2nsxcmpn0fzx277m5lk352cdf-gcc-13.3.0-lib/lib/libgcc_s.so.1 (0x000072bcf3768000)
        libpthread.so.0 => /nix/store/wlffq5p6mxxgfap10sav3ij936jzqm59-glibc-2.39-52/lib/libpthread.so.0 (0x000072bcf3761000)
        libm.so.6 => /nix/store/wlffq5p6mxxgfap10sav3ij936jzqm59-glibc-2.39-52/lib/libm.so.6 (0x000072bcf111a000)
        libc.so.6 => /nix/store/wlffq5p6mxxgfap10sav3ij936jzqm59-glibc-2.39-52/lib/libc.so.6 (0x000072bcf0f23000)
        /lib64/ld-linux-x86-64.so.2 => /nix/store/wlffq5p6mxxgfap10sav3ij936jzqm59-glibc-2.39-52/lib64/ld-linux-x86-64.so.2 (0x000072bcf387d000)
        libmtdev.so.1 => /nix/store/s1dggb3kn3g2rw01g9zbm248zgnw4k2y-mtdev-1.1.7/lib/libmtdev.so.1 (0x000072bcf14d9000)
        libevdev.so.2 => /nix/store/znk2rjs6hpxyv7v7fscrnxrjmzgkazbi-libevdev-1.13.2/lib/libevdev.so.2 (0x000072bcf14bb000)
        libwacom.so.9 => /nix/store/9y2wydmmgax0x1fds3cx2mp9aq373ms5-libwacom-2.12.2/lib/libwacom.so.9 (0x000072bcf14ab000)
        libgallium-24.2.1.so => /nix/store/hykhzxanlm463wpcw2546rp9ba8hjcz6-mesa-24.2.1/lib/libgallium-24.2.1.so (0x000072bcee800000)
        libwayland-server.so.0 => /nix/store/0xxjgp8nqgdwfnqbvavp1g61n8vbvyh1-wayland-1.23.0/lib/libwayland-server.so.0 (0x000072bcf1492000)
        libdrm.so.2 => /nix/store/n2aif1mg86whm5ls99w33558whkyh4za-libdrm-2.4.122/lib/libdrm.so.2 (0x000072bcf1478000)
        libexpat.so.1 => /nix/store/adhws9q73zbn1drflv6ddg0vm5m3mcqg-expat-2.6.2/lib/libexpat.so.1 (0x000072bcee7d3000)
        libxcb-randr.so.0 => /nix/store/9m44fpskp92p1fx1hww8dxlzk8pzal67-libxcb-1.17.0/lib/libxcb-randr.so.0 (0x000072bcf1465000)
        libz.so.1 => /nix/store/wfml6h84mna7sw9f6v7z0l60f4faxk8w-zlib-1.3.1/lib/libz.so.1 (0x000072bcee7b5000)
        libbz2.so.1 => /nix/store/9vllv8z6ynavf5vi2qz53c5pqb20kxs8-bzip2-1.0.8/lib/libbz2.so.1 (0x000072bcee7a2000)
        libpng16.so.16 => /nix/store/pff1zw34dsagywwhgrky8mfbdwq18cb8-libpng-apng-1.6.43/lib/libpng16.so.16 (0x000072bcee767000)
        libbrotlidec.so.1 => /nix/store/89f5a522ykhjrynx9x9zj6y6p47acf5k-brotli-1.1.0-lib/lib/libbrotlidec.so.1 (0x000072bcee758000)
        libgudev-1.0.so.0 => /nix/store/i02cklc48nfs4ca9519gr6jd5fgx9ygx-libgudev-238/lib/libgudev-1.0.so.0 (0x000072bcee74b000)
        libgobject-2.0.so.0 => /nix/store/d1jna110cihfr8024bgb504r5pvamrnv-glib-2.80.4/lib/libgobject-2.0.so.0 (0x000072bcee6e5000)
        libglib-2.0.so.0 => /nix/store/d1jna110cihfr8024bgb504r5pvamrnv-glib-2.80.4/lib/libglib-2.0.so.0 (0x000072bcee595000)
        libglapi.so.0 => /nix/store/hykhzxanlm463wpcw2546rp9ba8hjcz6-mesa-24.2.1/lib/libglapi.so.0 (0x000072bcee561000)
        libLLVM.so.18.1 => /nix/store/kqvwzfcfcvbknnjcqk2aip0hx99mfwyn-llvm-18.1.8-lib/lib/libLLVM.so.18.1 (0x000072bce5a00000)
        libzstd.so.1 => /nix/store/ib9sy6zprriqwwyi6ihsk0jclqyac9pk-zstd-1.5.6/lib/libzstd.so.1 (0x000072bce592c000)
        libxcb-dri3.so.0 => /nix/store/9m44fpskp92p1fx1hww8dxlzk8pzal67-libxcb-1.17.0/lib/libxcb-dri3.so.0 (0x000072bcee55a000)
        libsensors.so.5 => /nix/store/kiggm0vsahr3lrhii0p2ai011lkibprq-lm-sensors-3.6.0/lib/libsensors.so.5 (0x000072bcee549000)
        libdrm_radeon.so.1 => /nix/store/n2aif1mg86whm5ls99w33558whkyh4za-libdrm-2.4.122/lib/libdrm_radeon.so.1 (0x000072bcee53b000)
        libelf.so.1 => /nix/store/gc096h0wq9zm3m28np69rky6n2g3fbyh-elfutils-0.191/lib/libelf.so.1 (0x000072bcee51e000)
        libdrm_amdgpu.so.1 => /nix/store/n2aif1mg86whm5ls99w33558whkyh4za-libdrm-2.4.122/lib/libdrm_amdgpu.so.1 (0x000072bce5920000)
        libdrm_intel.so.1 => /nix/store/n2aif1mg86whm5ls99w33558whkyh4za-libdrm-2.4.122/lib/libdrm_intel.so.1 (0x000072bce58fa000)
        libffi.so.8 => /nix/store/jl1881nszkagiw2wzd2mwm379yjzzjga-libffi-3.4.6/lib/libffi.so.8 (0x000072bce58e9000)
        libxcb.so.1 => /nix/store/9m44fpskp92p1fx1hww8dxlzk8pzal67-libxcb-1.17.0/lib/libxcb.so.1 (0x000072bce58bd000)
        libXau.so.6 => /nix/store/89pslqsqcqb0d5994hnijvcaw2n5ldfy-libXau-1.0.11/lib/libXau.so.6 (0x000072bcee515000)
        libXdmcp.so.6 => /nix/store/d6hqx50dp95nv7rifmvx47rqhvnkxqly-libXdmcp-1.1.5/lib/libXdmcp.so.6 (0x000072bce58b5000)
        libbrotlicommon.so.1 => /nix/store/89f5a522ykhjrynx9x9zj6y6p47acf5k-brotli-1.1.0-lib/lib/libbrotlicommon.so.1 (0x000072bce5892000)
        libpcre2-8.so.0 => /nix/store/fvd0x6x3kn3c2bacvsjfg5d3vqllz8f3-pcre2-10.44/lib/libpcre2-8.so.0 (0x000072bce57f2000)
        librt.so.1 => /nix/store/wlffq5p6mxxgfap10sav3ij936jzqm59-glibc-2.39-52/lib/librt.so.1 (0x000072bce57ed000)
        libncursesw.so.6 => /nix/store/0l52axcc0k0pn1qpwyhnjz7pipidrwvr-ncurses-6.4.20221231/lib/libncursesw.so.6 (0x000072bce5777000)
        libxml2.so.2 => /nix/store/02kd12sydriqggzkbadqw3n0iq3va1nk-libxml2-2.13.3/lib/libxml2.so.2 (0x000072bce561b000)
        liblzma.so.5 => /nix/store/966vq3bp9pjzl6s50jl838gcirslrhdb-xz-5.6.2/lib/liblzma.so.5 (0x000072bce55ea000)
        libpciaccess.so.0 => /nix/store/s8xnyqwkj9dl82kk5xw1yx0077myzrgd-libpciaccess-0.18.1/lib/libpciaccess.so.0 (0x000072bce55de000)
```

My DISPLAY var is set as well
```bash
$ echo $DISPLAY
:0
```

However, preview still crashes:
```
_amdgpu_device_initialize: amdgpu_query_info(ACCEL_WORKING) failed (-13)
amdgpu: amdgpu_device_initialize failed.
Using Skia Software renderer
Rendering at 2256x1504
thread 'main' panicked at tools/lsp/preview/native.rs:122:40:
called `Result::unwrap()` on an `Err` value: OtherError("Error presenting fb: permission denied")
```

Are there any additional dependencies needed?

**Comment by hunger** [comment]
I am not an expert in any of this low-level graphics stuff, but those amdgpu lines are probably from somewhere inside mesa. No idea how to make that available in nixos though..

You could try using `strace` to see what exactly the application is trying to load and fails to find.

**Comment by tronical** [comment]
This is a slight red-herring. If there's an X11 display, the linuxkms backend should (and does) fail. The question is: Why does the winit x11 backend not work in your setup?

What kind of output do you get on the terminal if you set `SLINT_BACKEND=winit` and try to run the app?

**Comment by tronical** [comment]
> I'm just going to keep this bug open because I think the linuxkms error is less than ideal.
> 
> * It should ideally error out before, while creating the backend, so that the backend selector can fallback or display all the backend's errors. I don't know it that's possible thougyh

I believe that's already the case. The linuxkms backend is always last, so this happened _after_ the winit backend failed.

> * It should tell more info than just "Error presenting fb: permission denied".  Permission denied to what? What is it even trying to do.

I tweaked this slightly. However I think the real issue is not diagnostics but our inability to detect this error situation earlier. As it turns out, the system permitted us access to the GPU (despite X11 presumably already having access), and when we wanted to post something to the screen, we did get an error (good), but that was way to late (bad).

Perhaps there's some kind of additional testing we can do at linuxkms backend initialisation time to verify that we'll have success posting to the screen later.

I'm thinking, perhaps by simply clearing the screen with a black frame buffer perhaps.

**Comment by tronical** [comment]
@ogoffart would you be okay with that?

**Comment by ogoffart** [comment]
> I believe that's already the case. The linuxkms backend is always last, so this happened after the winit backend failed.

When I try on my computer to unser DISPLAY, I do indeed get error from both winit and linuxkms. But I get a different linuxkms error (see description of https://github.com/slint-ui/slint/pull/6093 which was actually made after i saw this issue pop in my notifications again)

> I tweaked this slightly

That's indeed better :-)
I guess the "permission denied" error doesn't come from us and we can't annotate it with the actual file or ressource that we were trying to access.

> Perhaps there's some kind of additional testing we can do at linuxkms backend initialisation time to verify that we'll have success posting to the screen later.

If that'd help for the common case, I think it'd be indeed great.
But It actually already worked for me (showed winit error as well). But my setup is different and maybe it is specific to some configuration because of NixOs

**Comment by tronical** [comment]
I think this could happen if you have two GPUs for example, one discrete and one integrated. Then you might have two `/dev/dri/card0|1` and maybe one is available.

I'll adjust the title and description of this issue accordingly.

**Comment by tronical** [comment]
Great. Yes, that is the optimal solution for your particular problem :-)

**Comment by tronical** [comment]
@bemyak since you're familiar with nix: Could you think of a way that we could improve our docs to explain - with a help of a settings file to copy & paste or download - how to quickly augment an existing nix environment to add all the necessary dependencies?

**Comment by tronical** [comment]
Thanks for the quick response:)

**Comment by hunger** [comment]
Experience shows that I am too stupid for the Nix language, sorry :-/

Where do you get the Slint extension for VSCode from?

The one from the store has a working slint-lsp in it -- provided all the dependencies are available of course. I guess that is where you run into problems?

Where would you get a slint-lsp from that works better on NixOS? The interface between the two is more stable nowadays than it used to be -- so I am not totally opposed to offering a way to configure a custom lsp within the extension anymore, but I doubt version 1.5.1 as packaged in nixpkgs will work well with current slint code.

**Comment by bemyak** [comment]
> Experience shows that I am too stupid for the Nix language, sorry :-/

I used to think the same way about myself, but then in CLICKED :sparkles: and now it all makes sense :sweat_smile: 

> Where do you get the Slint extension for VSCode from?

At the moment I'm using the one bundled with the extension.

> I guess that is where you run into problems?

Yes. Nix install all the deps into unconventional paths (`/nix/store/), so LSP can't find the libraries even though they are there.

> Where would you get a slint-lsp from that works better on NixOS?

A package from Nixpkgs was already compiled in a Nix environment, so it's aware of all these weird paths, and it will "just work".

One thing to note is that you don't have to manually update `slint-lsp` package, there's a [bot](https://github.com/r-ryantm) that does it automatically when it sees a new GitHub release or tag, but I don't know why it skips your package.

**Comment by hunger** [comment]
> I used to think the same way about myself, but then in CLICKED ✨ and now it all makes sense 😅

I was fascinated when I first heard of it, but I found it way too complex by design: It forces me to think about the state of every package individually. I prefer to think about the system as a whole.

> Yes. Nix install all the deps into unconventional paths (`/nix/store/), so LSP can't find the libraries even though they are there.

IIRC Nix creates link-farms to make it compatible with traditional software. Was that dropped since I played with it?

> One thing to note is that you don't have to manually update slint-lsp package, there's a [bot](https://github.com/r-ryantm) that does it automatically when it sees a new GitHub release or tag, but I don't know why it skips your package.

It should be trivial for you to jump in and maintain that package then ;-)

**Comment by bemyak** [comment]
> Was that dropped since I played with it?

No, it's not dropped, but it's not the default behavior. You can create "Filesystem Hierarchy Standard" environment for a package: https://ryantm.github.io/nixpkgs/builders/special/fhs-environments/. There are tools which do this (semi)automatically like [nix-alien](https://github.com/thiagokokada/nix-alien). However, nix-alien doesn't detect libraries that are linked dynamically at runtime (like `wayland`), so it wasn't too much of a help.

> It should be trivial for you to jump in and maintain that package then ;-)

I am at that stage of my life where I have about 30 minutes a day to program something for myself during evening commute in a bus :slightly_smiling_face: 
I will try to update the package when I'll scrape a bit more time, maybe during a weekend, sorry.

**Comment by ogoffart** [comment]
I'm closing this bug as the actionable part have been fixed.
