### ISSUE TITLE
Extension Fails to Start in WSL2 Ubuntu-22.04

### ISSUE THREAD

**Issue by cwolter97** [slint-ui/slint#4926]
Reproduction Steps:
- Install fresh Ubuntu-22.04 instance with WSL2
- Start VSCode in WSL2 distro
- Install slint extension

Extension Host (Remote) Output:
```console
2024-03-22 12:06:36.981 [info] ExtensionService#_doActivateExtension Slint.slint, startup: false, activationEvent: 'workspaceContains:{**/CMakeLists.txt,**/Cargo.toml,**/*.slint}'
2024-03-22 12:06:38.079 [error] Error: write EPIPE
	at afterWriteDispatched (node:internal/stream_base_commons:160:15)
	at writeGeneric (node:internal/stream_base_commons:151:3)
	at Socket._writeGeneric (node:net:931:11)
	at Socket._write (node:net:943:8)
	at writeOrBuffer (node:internal/streams/writable:392:12)
	at _write (node:internal/streams/writable:333:10)
	at Writable.write (node:internal/streams/writable:337:10)
	at /home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-jsonrpc/lib/node/ril.js:88:29
	at new Promise (<anonymous>)
	at WritableStreamWrapper.write (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-jsonrpc/lib/node/ril.js:78:16)
	at StreamMessageWriter.doWrite (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:99:33)
	at /home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:90:29
2024-03-22 12:06:38.080 [error] Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:914:19)
	at LanguageClient.stop (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:885:21)
	at LanguageClient.stop (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.doInitialize (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:867:27)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async LanguageClient.start (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:722:13)
2024-03-22 12:06:38.080 [error] Error: write EPIPE
	at /home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1088:44
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-22 12:06:38.092 [error] Error: Cannot call write after a stream was destroyed
	at new NodeError (node:internal/errors:405:5)
	at _write (node:internal/streams/writable:324:11)
	at Writable.write (node:internal/streams/writable:337:10)
	at /home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-jsonrpc/lib/node/ril.js:88:29
	at new Promise (<anonymous>)
	at WritableStreamWrapper.write (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-jsonrpc/lib/node/ril.js:78:16)
	at StreamMessageWriter.doWrite (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:99:33)
	at /home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:90:29
2024-03-22 12:06:38.093 [error] Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:914:19)
	at LanguageClient.stop (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:885:21)
	at LanguageClient.stop (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.doInitialize (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:867:27)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async LanguageClient.start (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:722:13)
2024-03-22 12:06:38.099 [error] Error: write EPIPE
	at afterWriteDispatched (node:internal/stream_base_commons:160:15)
	at writeGeneric (node:internal/stream_base_commons:151:3)
	at Socket._writeGeneric (node:net:931:11)
	at Socket._write (node:net:943:8)
	at writeOrBuffer (node:internal/streams/writable:392:12)
	at _write (node:internal/streams/writable:333:10)
	at Writable.write (node:internal/streams/writable:337:10)
	at /home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-jsonrpc/lib/node/ril.js:88:29
	at new Promise (<anonymous>)
	at WritableStreamWrapper.write (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-jsonrpc/lib/node/ril.js:78:16)
	at StreamMessageWriter.doWrite (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:99:33)
	at /home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:90:29
2024-03-22 12:06:38.099 [error] Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:914:19)
	at LanguageClient.stop (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:885:21)
	at LanguageClient.stop (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.doInitialize (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:867:27)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async LanguageClient.start (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:722:13)
2024-03-22 12:06:38.103 [error] Error: Cannot call write after a stream was destroyed
	at new NodeError (node:internal/errors:405:5)
	at _write (node:internal/streams/writable:324:11)
	at Writable.write (node:internal/streams/writable:337:10)
	at /home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-jsonrpc/lib/node/ril.js:88:29
	at new Promise (<anonymous>)
	at WritableStreamWrapper.write (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-jsonrpc/lib/node/ril.js:78:16)
	at StreamMessageWriter.doWrite (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:99:33)
	at /home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:90:29
2024-03-22 12:06:38.103 [error] Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:914:19)
	at LanguageClient.stop (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:885:21)
	at LanguageClient.stop (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.doInitialize (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:867:27)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async LanguageClient.start (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:722:13)
2024-03-22 12:06:38.108 [error] Error: write EPIPE
	at afterWriteDispatched (node:internal/stream_base_commons:160:15)
	at writeGeneric (node:internal/stream_base_commons:151:3)
	at Socket._writeGeneric (node:net:931:11)
	at Socket._write (node:net:943:8)
	at writeOrBuffer (node:internal/streams/writable:392:12)
	at _write (node:internal/streams/writable:333:10)
	at Writable.write (node:internal/streams/writable:337:10)
	at /home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-jsonrpc/lib/node/ril.js:88:29
	at new Promise (<anonymous>)
	at WritableStreamWrapper.write (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-jsonrpc/lib/node/ril.js:78:16)
	at StreamMessageWriter.doWrite (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:99:33)
	at /home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:90:29
2024-03-22 12:06:38.109 [error] Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:914:19)
	at LanguageClient.stop (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:885:21)
	at LanguageClient.stop (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.doInitialize (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:867:27)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async LanguageClient.start (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:722:13)
```

**Comment by ogoffart** [comment]
Thanks for filling a bug.

Looks like the slint-lsp process fails to start. or somehow crash.
Is there perhaps some error in the "Slint LSP" section of the "Output" tab in the bottom (see screenshot)?

![image](https://github.com/slint-ui/slint/assets/959326/f7fe2746-2152-4cd6-9d7f-e60896962b36)

**Comment by cwolter97** [comment]
Hello - 

```console
[Error - 12:28:52 PM] Client Slint LSP: connection to server is erroring. Shutting down server.
[Error - 12:28:52 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:914:19)
	at LanguageClient.stop (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:885:21)
	at LanguageClient.stop (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 12:28:52 PM] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 12:28:52 PM] Slint LSP client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Info  - 12:28:52 PM] Connection to server got closed. Server will restart.
true
/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/bin/slint-lsp-x86_64-unknown-linux-gnu: error while loading shared libraries: libxkbcommon.so.0: cannot open shared object file: No such file or directory
[Error - 12:28:52 PM] Server initialization failed.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 12:28:52 PM] Slint LSP client: couldn't create connection to server.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 12:28:52 PM] Restarting server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Info  - 12:28:52 PM] Connection to server got closed. Server will restart.
true
/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/bin/slint-lsp-x86_64-unknown-linux-gnu: error while loading shared libraries: libxkbcommon.so.0: cannot open shared object file: No such file or directory
[Error - 12:28:52 PM] Client Slint LSP: connection to server is erroring. Shutting down server.
[Error - 12:28:52 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:914:19)
	at LanguageClient.stop (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:885:21)
	at LanguageClient.stop (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 12:28:52 PM] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 12:28:52 PM] Slint LSP client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Error - 12:28:52 PM] Restarting server failed
  Message: write EPIPE
  Code: -32099 
[Info  - 12:28:52 PM] Connection to server got closed. Server will restart.
true
/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/bin/slint-lsp-x86_64-unknown-linux-gnu: error while loading shared libraries: libxkbcommon.so.0: cannot open shared object file: No such file or directory
[Error - 12:28:52 PM] Server initialization failed.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 12:28:52 PM] Slint LSP client: couldn't create connection to server.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 12:28:52 PM] Restarting server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Info  - 12:28:52 PM] Connection to server got closed. Server will restart.
true
/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/bin/slint-lsp-x86_64-unknown-linux-gnu: error while loading shared libraries: libxkbcommon.so.0: cannot open shared object file: No such file or directory
[Error - 12:28:52 PM] Client Slint LSP: connection to server is erroring. Shutting down server.
[Error - 12:28:52 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:914:19)
	at LanguageClient.stop (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:885:21)
	at LanguageClient.stop (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 12:28:52 PM] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 12:28:52 PM] Slint LSP client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Error - 12:28:52 PM] Restarting server failed
  Message: write EPIPE
  Code: -32099 
[Error - 12:28:52 PM] The Slint LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/bin/slint-lsp-x86_64-unknown-linux-gnu: error while loading shared libraries: libxkbcommon.so.0: cannot open shared object file: No such file or directory
```

Seems I was able to resolve the above by installing libxkbcommon via `sudo apt install libxkbcommon-x11-0`

Now I am getting:
```console
[Error - 12:33:03 PM] Client Slint LSP: connection to server is erroring. Shutting down server.
[Error - 12:33:03 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:914:19)
	at LanguageClient.stop (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:885:21)
	at LanguageClient.stop (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 12:33:03 PM] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 12:33:03 PM] Slint LSP client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Info  - 12:33:03 PM] Connection to server got closed. Server will restart.
true
/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/bin/slint-lsp-x86_64-unknown-linux-gnu: error while loading shared libraries: libinput.so.10: cannot open shared object file: No such file or directory
[Error - 12:33:03 PM] Server initialization failed.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 12:33:03 PM] Slint LSP client: couldn't create connection to server.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 12:33:03 PM] Restarting server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Info  - 12:33:03 PM] Connection to server got closed. Server will restart.
true
/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/bin/slint-lsp-x86_64-unknown-linux-gnu: error while loading shared libraries: libinput.so.10: cannot open shared object file: No such file or directory
[Error - 12:33:03 PM] Client Slint LSP: connection to server is erroring. Shutting down server.
[Error - 12:33:03 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:914:19)
	at LanguageClient.stop (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:885:21)
	at LanguageClient.stop (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 12:33:03 PM] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 12:33:03 PM] Slint LSP client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Error - 12:33:03 PM] Restarting server failed
  Message: write EPIPE
  Code: -32099 
[Info  - 12:33:03 PM] Connection to server got closed. Server will restart.
true
/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/bin/slint-lsp-x86_64-unknown-linux-gnu: error while loading shared libraries: libinput.so.10: cannot open shared object file: No such file or directory
[Error - 12:33:03 PM] Server initialization failed.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 12:33:03 PM] Slint LSP client: couldn't create connection to server.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 12:33:03 PM] Restarting server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Info  - 12:33:03 PM] Connection to server got closed. Server will restart.
true
/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/bin/slint-lsp-x86_64-unknown-linux-gnu: error while loading shared libraries: libinput.so.10: cannot open shared object file: No such file or directory
[Error - 12:33:03 PM] Client Slint LSP: connection to server is erroring. Shutting down server.
[Error - 12:33:03 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:914:19)
	at LanguageClient.stop (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:885:21)
	at LanguageClient.stop (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 12:33:03 PM] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 12:33:03 PM] Slint LSP client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Error - 12:33:03 PM] Restarting server failed
  Message: write EPIPE
  Code: -32099 
[Error - 12:33:03 PM] The Slint LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
/home/yiggy/.vscode-server/extensions/slint.slint-1.5.1/bin/slint-lsp-x86_64-unknown-linux-gnu: error while loading shared libraries: libinput.so.10: cannot open shared object file: No such file or directory
```

**Comment by ogoffart** [comment]
Sadly this doesn't contain the stderror from the slint-lsp. This should be in another tab.

**Comment by cwolter97** [comment]
This is the entirety of the output from `OUTPUT` -> `Slint LSP`

![image](https://github.com/slint-ui/slint/assets/4241748/b558bed4-d58e-46df-80f7-a829094c9fb5)

Currently reviewing the missing shared libraries it keeps complaining about and installing what seems to be missing. Strange that no other extension fails due to these.

**Comment by cwolter97** [comment]
So, after installing
- libxkbcommon-x11-0
- libinput10
- libgbm-dev

I am finally getting something new:
```console
thread 'main' panicked at /home/runner/work/slint/slint/target/x86_64-unknown-linux-gnu/release/build/slint-lsp-48cf121149beeaeb/out/main.rs:21603:49:
called `Result::unwrap()` on an `Err` value: Other("Error opening device: Permission denied (os error 13)")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 12:47:43 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
```

**Comment by cwolter97** [comment]
> This is the binary downloaded from Github? The Linux version will try to use Qt5, so installing that might fix the issue.

This is the [slint extension](https://github.com/slint-ui/slint/blob/master/editors/vscode) for VSCode

**Comment by robmwalsh** [comment]
I got the slint preview working in ubuntu with using WSL by installing `libinput-tools` and `libgbm-dev`, perhaps `libinput-tools` has something else you need?

**Comment by cwolter97** [comment]
As stated above, I was able to get the extension to work with exception of the preview feature. Still annoying that there was several dependencies I needed to install separate from the extension

**Comment by tronical** [comment]
You’re right. I think it might be time to build a variant of the lsp binary specifically for wsl. With Wayland disabled for the time being, as well as linuxkms (causing the dependencies issues).

**Comment by robmwalsh** [comment]
> As stated above, I was able to get the extension to work with exception of the preview feature. Still annoying that there was several dependencies I needed to install separate from the extension

I'm suggesting that if you install `libinput-tools` the preview feature may also work :)

**Comment by freethebee** [comment]
I am not sure if this is related, but I came across the current issue trying to solve problems with the lsp in neovim en wsl2 (opensuse tumbleweed). I installed slint_lsp through mason, as by the documentation. On my personal laptop running opensuse natively it works fine, but the exact same config in wsl2 did not. I installed the dependencies listed above to no avail. 

What works for me is 
```bash
$ sudo rm -r /tmp/.X11-unix
$ ln -s /mnt/wslg/.X11-unix /tmp/.X11-unix
```

https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg

**Comment by microhobby** [comment]
I'm facing the same issue with Debian. Everytime that I press "ctrl+s" it crash the  LSP server until it `The Slint server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.`:

```
Error running LSP server: Failed to convert path
[Info  - 12:19:07 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug. Please open an issue on https://github.com/slint-ui/slint/issues
[Error - 12:19:07 PM] Server process exited with code 0.
Error running LSP server: Failed to convert path
[Info  - 12:19:52 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug. Please open an issue on https://github.com/slint-ui/slint/issues
[Error - 12:19:52 PM] Server process exited with code 0.
Error running LSP server: Failed to convert path
[Info  - 12:22:41 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug. Please open an issue on https://github.com/slint-ui/slint/issues
[Error - 12:22:41 PM] Server process exited with code 0.
Error running LSP server: Failed to convert path
[Info  - 12:22:43 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug. Please open an issue on https://github.com/slint-ui/slint/issues
[Error - 12:22:43 PM] Server process exited with code 0.
Error running LSP server: Failed to convert path
[Info  - 12:22:45 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug. Please open an issue on https://github.com/slint-ui/slint/issues
[Error - 12:22:45 PM] Server process exited with code 0.
Error running LSP server: Failed to convert path
[Error - 12:22:46 PM] The Slint server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
The Slint Language Server crashed. This is a bug. Please open an issue on https://github.com/slint-ui/slint/issues
[Error - 12:22:46 PM] Server process exited with code 0.
```

@ogoffart let me know with kind of information or tests you guys need.

**Comment by microhobby** [comment]
> I'm facing the same issue with Debian. Everytime that I press "ctrl+s"

Oh wait, it seems that I had the Slint (nightly) installed on Windows side. And in fact what was crashing was the Windows side. Uninstalling from Windows side and maintaining only on WSL 2 fix it 🤦.

**Comment by tronical** [comment]
So there are two issues here. @cwolter97 ran into [`Error opening device: Permission denied (os error 13)`](https://github.com/slint-ui/slint/issues/4926#issuecomment-2015612949), which happens when there's no `DISPLAY`/`WAYLAND_DISPLAY` set. This is a WSL issue, but the proposed [workaround](https://github.com/slint-ui/slint/issues/4926#issuecomment-2144339780) should work until upstream somehow fixes this.

The issue @microhobby ran into, [`Error running LSP server: Failed to convert path`](https://github.com/slint-ui/slint/issues/4926#issuecomment-2605035800) seems to be that slint-lsp is aborting on Windows. @microhobby , can you confirm that you're seeing this issue when you're using VS code in windows and when the extension is installed there? Or is there some connection to WSL?

**Comment by microhobby** [comment]
@tronical I'm not sure, but seems that when we connect to WSL the Slint extension, from Windows side, is trying to do stuff there and is not being able to. This can be solve by setting the:

```
"extensionKind": [
    "workspace",
    "ui"
  ],
```

to:

```
"extensionKind": [
    "workspace"
  ],
```

This way the VS Code will give preference, and will force the installation of the extension on the remote connection instead of trying to use the Windows side.

**Comment by ogoffart** [comment]
Another issue with "Failed to convert path" : https://github.com/slint-ui/slint/issues/7333

**Comment by ogoffart** [comment]
Closing as duplicate of #7333 and #8089

Please open a new issue if this still happen with Slint >= 1.15 with the actual URL that cannot be converted which is now part of the panic message.
