### ISSUE TITLE
rustrover plugin error

### ISSUE THREAD

**Issue by langzime** [slint-ui/slint#6203]
with rust
using rustrover plugin

```  java
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'dev.slint.ideaplugin.ide.actions.PreviewAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: dev.slint.ideaplugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

```

**Comment by ogoffart** [comment]
The rustrover plugin is a third party plugin not part of this repository.
https://github.com/kizeevov/slint-idea-plugin

Since the error message points to error specific to this plugin rather than to Slint, please report the issue on that repository instead.

I'm closing this issue in this repository because this is not actionable for us, but thanks anyway for reporting.

(Please add a link to this issue when reporting the issue in the other repository)
