### ISSUE TITLE
Crash when source element of callback gets deleted

### ISSUE THREAD

**Issue by ubruhin** [slint-ui/slint#6426]
This code:

```slint
import { Button } from "std-widgets.slint";

export component Example inherits Window {
    width: 200px;
    height: 200px;

    popup := PopupWindow {
        width: 100px;
        height: 100px;
        Rectangle {
            background: gray;
            Text {
                text: "Hello World";
            }
        }
    }

    touch := TouchArea {
        if touch.has-hover: Button {
            text: "Click me";
            clicked => {
                popup.show();
            }
        }
    }
}
```

Causes the LSP to crash when clicking on the button:

```
thread 'main' panicked at internal/interpreter/eval.rs:1527:26:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 5:35:31 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug. Please open an issue on https://github.com/slint-ui/slint/issues
The Slint Language Server crashed. This is a bug. Please open an issue on https://github.com/slint-ui/slint/issues
The Slint Language Server crashed. This is a bug. Please open an issue on https://github.com/slint-ui/slint/issues
```

I think the problem is somehow related to the conditional `if touch.has-hover:` which causes the button being destroyed at the moment the popup shows up. Somehow it also seems to be related to the `Text{}` element - if I remove it, it does not crash.

A workaround is to remove the conditional and use `visible: touch.has-hover;` instead.

I didn't experience the crash when compiling & running my C++ application (works as intended) but as we know from C++, this doesn't mean the absence of an illegal memory access...

---

Slint 1.8.0
Linux x64
ALso reproducible in https://releases.slint.dev/1.8.0/editor/

**Comment by ogoffart** [comment]
Thanks for the bug report.
I can reproduce it easily.
The crash happens when a binding within the popup try to access a global  (for example the popup's Text's text binding trying to access the color from the Palette global)
As far as my investigation goes, it seems to be two problem
 1. The popup has the wrong parent: it appears that the popup is parented to the destroyed item instead of the root)
 2. Although even if the parent get destroyed, then it should still not panic.

**Comment by ubruhin** [comment]
Here another similar problem :see_no_evil: 

```slint
export component AppWindow inherits Window {

    out property <length> scene-width;

    HorizontalLayout {
        if true: Rectangle {
            changed width => {
                scene-width = self.width;
            }
        }
    }
}
```

WIth a different error message:

```
thread 'main' panicked at /home/runner/work/slint/slint/internal/core/model.rs:928:38:
already borrowed: BorrowMutError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 10:23:16 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug. Please open an issue on https://github.com/slint-ui/slint/issues
The Slint Language Server crashed. This is a bug. Please open an issue on https://github.com/slint-ui/slint/issues
The Slint Language Server crashed. This is a bug. Please open an issue on https://github.com/slint-ui/slint/issues
```

Slint 1.8.0 LSP in VSCode extension on Linux

**Comment by 0x6e** [comment]
I have a similar case which appears to be the same crash:

```
import { StyleMetrics, SpinBox, VerticalBox } from "std-widgets.slint";

export global Data {
    in-out property <int> r1;
    pure callback r1-change-requested(int);
}

component DataRow inherits HorizontalLayout {
    in property <string> title;
    in-out property <int> value <=> spinBox.value;
    callback edited <=> spinBox.edited;

    spacing: StyleMetrics.layout-spacing;

    Text {
        text: "\{title}: \{value}";
        vertical-alignment: TextVerticalAlignment.center;
    }

    spinBox := SpinBox { }
}

export component Demo {
    VerticalBox {
        alignment: start;
        DataRow {
            title: "Data.r1";
            value <=> Data.r1;

            edited(value) => {
                Data.r1-change-requested(value);
            }
        }
    }
}
```


```
thread 'main' panicked at internal/interpreter/eval.rs:1772:71:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:        0x10dcd2a8e - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h17237c63d1a69dcb
   1:        0x10d328db3 - core::fmt::write::h30aaf9daa2b08429
   2:        0x10dcd0e62 - std::io::Write::write_fmt::hb170de60ea76b27f
   3:        0x10dcd28c3 - std::sys::backtrace::BacktraceLock::print::h987b7f42d6b8a667
   4:        0x10dcd148e - std::panicking::default_hook::h6b7909227071dd78
   5:        0x10dcc38a5 - slint_lsp::main::{{closure}}::h67b8084efa61e1de
   6:        0x10dcd0c09 - std::panicking::rust_panic_with_hook::hc6bfd990e349125f
   7:        0x10dd051e5 - std::panicking::begin_panic_handler::{{closure}}::hc31bc6dc768176f9
   8:        0x10dd05179 - std::sys::backtrace::__rust_end_short_backtrace::hef21f4a0cd77e47f
   9:        0x10dd05c1c - _rust_begin_unwind
  10:        0x10e33bdef - core::panicking::panic_fmt::h7b5799c67973413f
  11:        0x10e33be44 - core::panicking::panic::ha707a7b82a6bde64
  12:        0x10e33c048 - core::option::unwrap_failed::h4251d206eaa604a8
  13:        0x10d98eac5 - slint_interpreter::eval::enclosing_component_for_element::h86b2669458d47761
  14:        0x10d98dfbc - slint_interpreter::eval::enclosing_component_instance_for_element::h0b644397c0d788f6
  15:        0x10d99f0a5 - slint_interpreter::eval::call_function::haf8213cc241a373e
  16:        0x10d990cf7 - slint_interpreter::eval::eval_expression::hdc181c0ce426aa74
  17:        0x10d98ee5f - slint_interpreter::eval::eval_expression::hdc181c0ce426aa74
  18:        0x10d9868ec - i_slint_core::properties::change_tracker::ChangeTracker::init::evaluate::h4a75cd062164306c
  19:        0x10d6d31d0 - std::thread::local::LocalKey<T>::with::hd261bf24187777f3
  20:        0x10d6c87a0 - i_slint_core::window::WindowInner::process_mouse_input::h708a2959fae776c1
  21:        0x10d40d436 - <i_slint_backend_winit::event_loop::ActiveEventLoopSetterDuringEventProcessing<Handler> as winit::application::ApplicationHandler<Event>>::window_event::hf92b9856c4dcb6dc
  22:        0x10d42c8cd - winit::platform_impl::macos::event_loop::map_user_event::{{closure}}::h67a6426f3317661e
  23:        0x10de08f2a - winit::platform_impl::macos::event_handler::EventHandler::handle_event::hac7abc09652e6259
  24:        0x10de07a7b - winit::platform_impl::macos::app_state::ApplicationDelegate::maybe_queue_event::h384a7a7b4c0d4fab
  25:        0x10de04dc7 - winit::platform_impl::macos::view::WinitView::mouse_click::h352411c2d1b28b32
  26:     0x7ff80bad93c8 - <unknown>
  27:     0x7ff80af213ad - <unknown>
  28:     0x7ff80af20fb5 - <unknown>
  29:     0x7ff80b855ec9 - <unknown>
  30:        0x10de0cbd2 - winit::platform_impl::macos::app::WinitApplication::send_event::h370d56a1439d1374
  31:     0x7ff80b3b9cc3 - <unknown>
  32:     0x7ff80adbaf45 - <unknown>
  33:        0x10d4224a2 - <i_slint_backend_winit::Backend as i_slint_core::platform::Platform>::run_event_loop::he054a8f493d8699c
  34:        0x10dcbfcca - slint_lsp::main::h43bf80ee4845a5c1
  35:        0x10dcb4056 - std::sys::backtrace::__rust_begin_short_backtrace::hdfd98b9a1a80218f
  36:        0x10dcbd264 - _main
  37:     0x7ff806f8c530 - <unknown>
[Info  - 17:20:12] Connection to server got closed. Server will restart.
```
