### ISSUE TITLE
Panic `assertion failed: lhs_lookup.is_local_to_component` in `internal/compiler/passes/resolving.rs`

### ISSUE THREAD

**Issue by qarmin** [slint-ui/slint#6519]
File content(at the bottom should be attached raw, not formatted file - github removes some non-printable characters, so copying from here may not work):
```
component Button{property<bool>checked}export component C{in property<b in
Button{checked<=>in
```

Source code of program that trying to compile code - https://github.com/qarmin/Automated-Fuzzer/blob/master/src/crates/slint/src/main.rs

command
```
cargo install --git https://github.com/qarmin/Automated-Fuzzer/ slint
RUST_BACKTRACE=1 timeout -v 100 slint TEST___FILE.slint
```

cause this
```
thread 'main' panicked at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/ccf5f04/internal/compiler/passes/resolving.rs:1583:41:
assertion failed: lhs_lookup.is_local_to_component
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb4e2346748e1760f74fcaa27b42431e0b95f8f3/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eb4e2346748e1760f74fcaa27b42431e0b95f8f3/library/core/src/panicking.rs:74:14
   2: core::panicking::panic
             at /rustc/eb4e2346748e1760f74fcaa27b42431e0b95f8f3/library/core/src/panicking.rs:148:5
   3: i_slint_compiler::passes::resolving::resolve_two_way_bindings::{{closure}}
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/ccf5f04/internal/compiler/passes/resolving.rs:1583:41
   4: i_slint_compiler::object_tree::recurse_elem
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/ccf5f04/internal/compiler/object_tree.rs:2078:17
   5: i_slint_compiler::object_tree::recurse_elem
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/ccf5f04/internal/compiler/object_tree.rs:2080:9
   6: i_slint_compiler::passes::resolving::resolve_two_way_bindings
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/ccf5f04/internal/compiler/passes/resolving.rs:1526:9
   7: i_slint_compiler::passes::resolving::resolve_expressions
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/ccf5f04/internal/compiler/passes/resolving.rs:83:5
   8: i_slint_compiler::passes::run_import_passes
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/ccf5f04/internal/compiler/passes.rs:288:5
   9: i_slint_compiler::compile_syntax_node::{{closure}}
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/ccf5f04/internal/compiler/lib.rs:300:9
  10: spin_on::spin_on
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spin_on-0.1.1/src/lib.rs:78:38
  11: slint::check_file
             at ./src/crates/slint/src/main.rs:45:21
  12: slint::main
             at ./src/crates/slint/src/main.rs:25:9
  13: core::ops::function::FnOnce::call_once
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

##### Automatic Fuzzer note, output status "None", output signal "Some(6)"
```

[compressed.zip](https://github.com/user-attachments/files/17338090/compressed.zip)

**Comment by hunger** [comment]
Looks like you found some problems with the fuzzer! Really nice, thank you for putting in the effort.
