### ISSUE TITLE
`assertion failed: !matches!(e, Expression::Invalid)` in `internal/compiler/passes/default_geometry.rs`

### ISSUE THREAD

**Issue by qarmin** [slint-ui/slint#6590]
File content(at the bottom should be attached raw, not formatted file - github removes some non-printable characters, so copying from here may not work):
```
component A inherits Window{preferred-height:x;Image{}}
```

Source code of program that trying to compile code - https://github.com/qarmin/Automated-Fuzzer/blob/master/src/crates/slint/src/main.rs

command
```
cargo install --git https://github.com/qarmin/Automated-Fuzzer/ slint
RUST_BACKTRACE=1 timeout -v 100 slint TEST___FILE.slint
```

cause this
```
thread 'main' panicked at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/5032ff1/internal/compiler/passes/default_geometry.rs:295:13:
assertion failed: !matches!(e, Expression::Invalid)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e92993dbb43f0a5d17fe56e2d82f90435d6521c8/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/e92993dbb43f0a5d17fe56e2d82f90435d6521c8/library/core/src/panicking.rs:74:14
   2: core::panicking::panic
             at /rustc/e92993dbb43f0a5d17fe56e2d82f90435d6521c8/library/core/src/panicking.rs:148:5
   3: i_slint_compiler::passes::default_geometry::merge_explicit_constraints
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/5032ff1/internal/compiler/passes/default_geometry.rs:295:13
   4: i_slint_compiler::passes::default_geometry::gen_layout_info_prop
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/5032ff1/internal/compiler/passes/default_geometry.rs:225:9
   5: i_slint_compiler::passes::default_geometry::default_geometry::{{closure}}
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/5032ff1/internal/compiler/passes/default_geometry.rs:40:13
   6: i_slint_compiler::object_tree::recurse_elem_including_sub_components::{{closure}}
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/5032ff1/internal/compiler/object_tree.rs:2100:9
   7: i_slint_compiler::object_tree::recurse_elem
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/5032ff1/internal/compiler/object_tree.rs:2076:17
   8: i_slint_compiler::object_tree::recurse_elem_including_sub_components
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/5032ff1/internal/compiler/object_tree.rs:2088:5
   9: i_slint_compiler::passes::default_geometry::default_geometry
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/5032ff1/internal/compiler/passes/default_geometry.rs:26:5
  10: i_slint_compiler::passes::run_passes::{{closure}}::{{closure}}
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/5032ff1/internal/compiler/passes.rs:128:9
  11: i_slint_compiler::object_tree::Document::visit_all_used_components
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/5032ff1/internal/compiler/object_tree.rs:261:13
  12: i_slint_compiler::passes::run_passes::{{closure}}
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/5032ff1/internal/compiler/passes.rs:123:5
  13: i_slint_compiler::compile_syntax_node::{{closure}}
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/5032ff1/internal/compiler/lib.rs:299:76
  14: spin_on::spin_on
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spin_on-0.1.1/src/lib.rs:78:38
  15: slint::check_file
             at ./src/crates/slint/src/main.rs:45:21
  16: slint::main
             at ./src/crates/slint/src/main.rs:25:9
  17: core::ops::function::FnOnce::call_once
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

##### Automatic Fuzzer note, output status "None", output signal "Some(6)"
```
[compressed.zip](https://github.com/user-attachments/files/17445370/compressed.zip)

**Comment by JoeySoprano420** [comment]
Undubscribe
