### ISSUE TITLE
Panic `end() called without begin()` in `lyon_path-1.0.5/src/private.rs`

### ISSUE THREAD

**Issue by qarmin** [slint-ui/slint#6591]
File content(at the bottom should be attached raw, not formatted file - github removes some non-printable characters, so copying from here may not work):
```
T:=Path{commands:"0 0M";}
```

Source code of program that trying to compile code - https://github.com/qarmin/Automated-Fuzzer/blob/master/src/crates/slint/src/main.rs

command
```
cargo install --git https://github.com/qarmin/Automated-Fuzzer/ slint
RUST_BACKTRACE=1 timeout -v 100 slint TEST___FILE.slint
```

cause this
```
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lyon_path-1.0.5/src/private.rs:37:13:
end() called without begin()
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e92993dbb43f0a5d17fe56e2d82f90435d6521c8/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/e92993dbb43f0a5d17fe56e2d82f90435d6521c8/library/core/src/panicking.rs:74:14
   2: core::panicking::panic
             at /rustc/e92993dbb43f0a5d17fe56e2d82f90435d6521c8/library/core/src/panicking.rs:148:5
   3: lyon_path::private::DebugValidator::end
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lyon_path-1.0.5/src/private.rs:37:13
   4: <lyon_path::path::BuilderImpl as lyon_path::builder::PathBuilder>::end
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lyon_path-1.0.5/src/path.rs:536:24
   5: <lyon_path::builder::NoAttributes<B> as lyon_path::builder::PathBuilder>::end
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lyon_path-1.0.5/src/builder.rs:390:9
   6: lyon_extra::parser::PathParser::parse
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lyon_extra-1.0.2/src/parser.rs:169:13
   7: i_slint_compiler::passes::compile_paths::compile_path_from_string_literal
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/5032ff1/internal/compiler/passes/compile_paths.rs:147:5
   8: i_slint_compiler::passes::compile_paths::compile_paths::{{closure}}
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/5032ff1/internal/compiler/passes/compile_paths.rs:69:27
   9: i_slint_compiler::object_tree::recurse_elem
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/5032ff1/internal/compiler/object_tree.rs:2076:17
  10: i_slint_compiler::passes::compile_paths::compile_paths
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/5032ff1/internal/compiler/passes/compile_paths.rs:31:5
  11: i_slint_compiler::passes::run_passes::{{closure}}::{{closure}}
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/5032ff1/internal/compiler/passes.rs:90:9
  12: i_slint_compiler::object_tree::Document::visit_all_used_components
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/5032ff1/internal/compiler/object_tree.rs:261:13
  13: i_slint_compiler::passes::run_passes::{{closure}}
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/5032ff1/internal/compiler/passes.rs:89:5
  14: i_slint_compiler::compile_syntax_node::{{closure}}
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/5032ff1/internal/compiler/lib.rs:299:76
  15: spin_on::spin_on
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spin_on-0.1.1/src/lib.rs:78:38
  16: slint::check_file
             at ./src/crates/slint/src/main.rs:45:21
  17: slint::main
             at ./src/crates/slint/src/main.rs:25:9
  18: core::ops::function::FnOnce::call_once
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

##### Automatic Fuzzer note, output status "None", output signal "Some(6)"
```
[compressed.zip](https://github.com/user-attachments/files/17445370/compressed.zip)

**Comment by ogoffart** [comment]
Thanks for fizzing Slint.
This issue seems to be a bug in the lyon library.
Reported as https://github.com/nical/lyon/issues/919
