### ISSUE TITLE
Panic when drawing text in software renderer on embedded esp32s3

### ISSUE THREAD

**Issue by yanshay** [slint-ui/slint#6643]
The following panic occurs in my app from time to time, I can't reproduce it, happens only once every a few tens of runs:

Seems to be related to text drawing (because of textlayout.rs in the backtrace) so maybe has to do with exact text, or font.

I'm on a Mac and using the default font as collected by the slint compiler. Maybe several sizes of fonts if its relevant.
The app runs on esp32s3 if it's of any relevance.

```
====================== PANIC ======================
panicked at /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-core-1.8.0/software_renderer.rs:1937:49:
range start index 4294967044 out of range for slice of length 1332

Backtrace:

0x420dfa5a
0x420dfa5a - <core::ops::range::RangeFrom<usize> as core::slice::index::SliceIndex<[T]>>::index
    at /Users/user/.rustup/toolchains/esp/lib/rustlib/src/rust/library/core/src/slice/index.rs:492
0x420de597
0x420de597 - i_slint_core::textlayout::TextParagraphLayout<Font>::layout_lines
    at /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-core-1.8.0/textlayout.rs:268
0x420e0d80
0x420e0d80 - <i_slint_core::software_renderer::SceneBuilder<T> as i_slint_core::item_rendering::ItemRenderer>::draw_text
    at /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-core-1.8.0/software_renderer.rs:2365
0x420dcf75
0x420dcf75 - i_slint_core::properties::PropertyTracker<DirtyHandler>::evaluate
    at /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-core-1.8.0/properties.rs:1451
0x420b7fd5
0x420b7fd5 - <i_slint_core::items::text::SimpleText as i_slint_core::items::Item_vtable_mod::Item>::render
    at /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-core-1.8.0/items/text.rs:278
0x420c1056
0x420c1056 - i_slint_core::items::Item_vtable_mod::ItemTO::render
    at /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-core-1.8.0/items.rs:108
0x42069d84
0x42069d84 - i_slint_core::item_tree::ItemVisitor_vtable_mod::ItemVisitorTO::visit_item
    at /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-core-1.8.0/item_tree.rs:989
0x42016eb8
0x42016eb8 - i_slint_core::item_tree::ItemTree_vtable_mod::ItemTreeVTable::new::visit_children_item
    at /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-core-1.8.0/item_tree.rs:44
0x420c107d
0x420c107d - i_slint_core::item_tree::ItemTree_vtable_mod::ItemTreeTO::visit_children_item
    at /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-core-1.8.0/item_tree.rs:44
0x42069d24
0x42069d24 - i_slint_core::item_tree::ItemVisitor_vtable_mod::ItemVisitorTO::visit_item
    at /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-core-1.8.0/item_tree.rs:989

```

**Comment by ogoffart** [comment]
Thanks for filing an issue.
Looks like something went wrong when computing the offsets at which to start drawing the image.
It would be really nice if there was a testcase to reproduce the issue.
But what I can do is to refactor a bit this code to be more resilient

**Comment by yanshay** [comment]
Thanks, unfortunately this happens randomly at different situations in a quite large program so I can't create a test case.
But on the next release I will update and will update if it still happens or see other issues.
