### ISSUE TITLE
Software renderer crashes when resizing window

### ISSUE THREAD

**Issue by dgulotta** [slint-ui/slint#6932]
### Bug Description

The software renderer crashes if I resize the window.

```
thread 'main' panicked at /home/dan/.cargo/git/checkouts/slint-8153123e5dffa129/7286169/internal/core/software_renderer.rs:527:33:
range end index 902 out of range for slice of length 901
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::slice::index::slice_end_index_len_fail_rt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/slice/index.rs:65:5
   3: core::slice::index::slice_end_index_len_fail
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/slice/index.rs:58:5
   4: <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index_mut
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/slice/index.rs:478:13
   5: core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/slice/index.rs:28:9
   6: i_slint_core::software_renderer::SoftwareRenderer::render::{{closure}}
             at /home/dan/.cargo/git/checkouts/slint-8153123e5dffa129/7286169/internal/core/software_renderer.rs:527:33
   7: i_slint_core::window::WindowInner::draw_contents::{{closure}}
             at /home/dan/.cargo/git/checkouts/slint-8153123e5dffa129/7286169/internal/core/window.rs:917:21
   8: i_slint_core::properties::_::<impl i_slint_core::properties::CURRENT_BINDING>::set
             at /home/dan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/scoped-tls-hkt-0.1.5/src/lib.rs:258:21
   9: i_slint_core::properties::PropertyTracker<DirtyHandler>::evaluate_as_dependency_root
             at /home/dan/.cargo/git/checkouts/slint-8153123e5dffa129/7286169/internal/core/properties.rs:1467:17
  10: i_slint_core::window::WindowInner::draw_contents
             at /home/dan/.cargo/git/checkouts/slint-8153123e5dffa129/7286169/internal/core/window.rs:909:14
  11: i_slint_core::software_renderer::SoftwareRenderer::render
             at /home/dan/.cargo/git/checkouts/slint-8153123e5dffa129/7286169/internal/core/software_renderer.rs:497:9
  12: <i_slint_backend_winit::renderer::sw::WinitSoftwareRenderer as i_slint_backend_winit::renderer::WinitCompatibleRenderer>::render
             at /home/dan/.cargo/git/checkouts/slint-8153123e5dffa129/7286169/internal/backends/winit/renderer/sw.rs:114:13
  13: i_slint_backend_winit::winitwindowadapter::WinitWindowAdapter::draw
             at /home/dan/.cargo/git/checkouts/slint-8153123e5dffa129/7286169/internal/backends/winit/winitwindowadapter.rs:491:9
  14: <i_slint_backend_winit::event_loop::EventLoopState as winit::application::ApplicationHandler<i_slint_backend_winit::SlintUserEvent>>::window_event
             at /home/dan/.cargo/git/checkouts/slint-8153123e5dffa129/7286169/internal/backends/winit/event_loop.rs:325:35
  15: <&mut A as winit::application::ApplicationHandler<T>>::window_event
             at /home/dan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/application.rs:250:9
  16: <i_slint_backend_winit::event_loop::ActiveEventLoopSetterDuringEventProcessing<Handler> as winit::application::ApplicationHandler<Event>>::window_event::{{closure}}
             at /home/dan/.cargo/git/checkouts/slint-8153123e5dffa129/7286169/internal/backends/winit/event_loop.rs:618:40
  17: i_slint_backend_winit::event_loop::_::<impl i_slint_backend_winit::event_loop::CURRENT_WINDOW_TARGET>::set
             at /home/dan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/scoped-tls-hkt-0.1.5/src/lib.rs:258:21
  18: <i_slint_backend_winit::event_loop::ActiveEventLoopSetterDuringEventProcessing<Handler> as winit::application::ApplicationHandler<Event>>::window_event
             at /home/dan/.cargo/git/checkouts/slint-8153123e5dffa129/7286169/internal/backends/winit/event_loop.rs:617:9
  19: winit::event_loop::dispatch_event_for_app
             at /home/dan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/event_loop.rs:642:52
  20: winit::platform::run_on_demand::EventLoopExtRunOnDemand::run_app_on_demand::{{closure}}
             at /home/dan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform/run_on_demand.rs:76:13
  21: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:294:13
  22: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:294:13
  23: winit::platform_impl::linux::x11::EventLoop<T>::single_iteration
             at /home/dan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform_impl/linux/x11/mod.rs:563:17
  24: winit::platform_impl::linux::x11::EventLoop<T>::poll_events_with_timeout
             at /home/dan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform_impl/linux/x11/mod.rs:504:9
  25: winit::platform_impl::linux::x11::EventLoop<T>::pump_events
             at /home/dan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform_impl/linux/x11/mod.rs:424:13
  26: winit::platform_impl::linux::x11::EventLoop<T>::run_on_demand
             at /home/dan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform_impl/linux/x11/mod.rs:385:19
  27: winit::platform_impl::linux::EventLoop<T>::run_on_demand
             at /home/dan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform_impl/linux/mod.rs:813:56
  28: <winit::event_loop::EventLoop<T> as winit::platform::run_on_demand::EventLoopExtRunOnDemand>::run_on_demand
             at /home/dan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform/run_on_demand.rs:89:9
  29: winit::platform::run_on_demand::EventLoopExtRunOnDemand::run_app_on_demand
             at /home/dan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform/run_on_demand.rs:75:9
  30: i_slint_backend_winit::event_loop::EventLoopState::run
             at /home/dan/.cargo/git/checkouts/slint-8153123e5dffa129/7286169/internal/backends/winit/event_loop.rs:696:13
  31: <i_slint_backend_winit::Backend as i_slint_core::platform::Platform>::run_event_loop
             at /home/dan/.cargo/git/checkouts/slint-8153123e5dffa129/7286169/internal/backends/winit/lib.rs:443:25
  32: slint::run_event_loop::{{closure}}
             at /home/dan/.cargo/git/checkouts/slint-8153123e5dffa129/7286169/api/rs/slint/lib.rs:245:49
  33: i_slint_backend_selector::with_platform::{{closure}}
             at /home/dan/.cargo/git/checkouts/slint-8153123e5dffa129/7286169/internal/backends/selector/lib.rs:203:31
  34: i_slint_core::context::with_global_context::{{closure}}
             at /home/dan/.cargo/git/checkouts/slint-8153123e5dffa129/7286169/internal/core/context.rs:103:25
  35: std::thread::local::LocalKey<T>::try_with
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/thread/local.rs:283:12
  36: std::thread::local::LocalKey<T>::with
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/thread/local.rs:260:9
  37: i_slint_core::context::with_global_context
             at /home/dan/.cargo/git/checkouts/slint-8153123e5dffa129/7286169/internal/core/context.rs:102:5
  38: i_slint_backend_selector::with_global_context
             at /home/dan/.cargo/git/checkouts/slint-8153123e5dffa129/7286169/internal/backends/selector/lib.rs:210:18
  39: i_slint_backend_selector::with_platform
             at /home/dan/.cargo/git/checkouts/slint-8153123e5dffa129/7286169/internal/backends/selector/lib.rs:203:5
  40: slint::run_event_loop
             at /home/dan/.cargo/git/checkouts/slint-8153123e5dffa129/7286169/api/rs/slint/lib.rs:245:5
  41: <slint_test::slint_generatedAppWindow::AppWindow as i_slint_core::api::ComponentHandle>::run
             at ./target/debug/build/slint-test-0cba2a0b8452f95a/out/app-window.rs:328:14
  42: slint_test::main
             at ./src/main.rs:10:5
  43: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
```

### Reproducible Code (if applicable)

```slint
export component AppWindow inherits Window {
}
```

### Environment Details

- Slint Version: 1.8.0 and master
- Platform/OS: Void Linux; Xfce 4.18 on X11
- Programming Language: Rust
- Backend/Renderer: Winit+Software

**Comment by ogoffart** [comment]
I had seen that before. This can be reproduced if the screen's scale factor is not a round number  (Can reproduce it with 1.3,  but not with 1 or 1.5 or 2)
I think this happens because the size might be converted to different value in different places.
