### ISSUE TITLE
Panic `private functions must be local and defined` in `internal/compiler/passes/purity_check.rs`

### ISSUE THREAD

**Issue by qarmin** [slint-ui/slint#6979]
### Bug Description

File content(at the bottom should be attached raw, not formatted file - github removes some non-printable characters, so copying from here may not work):
```
SubElement := Rectangle {
    forward_focus: input;
   input := TextInput {
   }
}TestCase := Rectangle {
  pure callback focus_input2();    focus_input2 => { input2.focus(); }
input2 := SubElement {}}
```

Source code of program that trying to compile code - https://github.com/qarmin/Automated-Fuzzer/blob/master/src/crates/slint/src/main.rs

command
```
cargo install --git https://github.com/qarmin/Automated-Fuzzer/ slint
RUST_BACKTRACE=1 timeout -v 100 slint TEST___FILE.slint
```

cause this
```
thread 'main' panicked at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/98e5df9/internal/compiler/passes/purity_check.rs:75:33:
private functions must be local and defined
stack backtrace:
   0: rust_begin_unwind
             at /rustc/dff3e7ccd4a18958c938136c4ccdc853fcc86194/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/dff3e7ccd4a18958c938136c4ccdc853fcc86194/library/core/src/panicking.rs:76:14
   2: i_slint_compiler::passes::purity_check::ensure_pure::{{closure}}
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/98e5df9/internal/compiler/passes/purity_check.rs:75:33
   3: i_slint_compiler::expression_tree::Expression::visit_recursive
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/98e5df9/internal/compiler/expression_tree.rs:1016:9
   4: i_slint_compiler::expression_tree::Expression::visit_recursive::{{closure}}
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/98e5df9/internal/compiler/expression_tree.rs:1017:24
   5: i_slint_compiler::expression_tree::Expression::visit
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/98e5df9/internal/compiler/expression_tree.rs:837:17
   6: i_slint_compiler::expression_tree::Expression::visit_recursive
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/98e5df9/internal/compiler/expression_tree.rs:1017:9
   7: i_slint_compiler::expression_tree::Expression::visit_recursive::{{closure}}
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/98e5df9/internal/compiler/expression_tree.rs:1017:24
   8: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/iter/macros.rs:254:21
   9: i_slint_compiler::expression_tree::Expression::visit
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/98e5df9/internal/compiler/expression_tree.rs:834:17
  10: i_slint_compiler::expression_tree::Expression::visit_recursive
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/98e5df9/internal/compiler/expression_tree.rs:1017:9
  11: i_slint_compiler::passes::purity_check::ensure_pure
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/98e5df9/internal/compiler/passes/purity_check.rs:45:5
  12: i_slint_compiler::passes::purity_check::purity_check::{{closure}}::{{closure}}
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/98e5df9/internal/compiler/passes/purity_check.rs:26:29
  13: i_slint_compiler::object_tree::visit_element_expressions::visit_element_expressions_simple
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/98e5df9/internal/compiler/object_tree.rs:2194:13
  14: i_slint_compiler::object_tree::visit_element_expressions
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/98e5df9/internal/compiler/object_tree.rs:2220:5
  15: i_slint_compiler::passes::purity_check::purity_check::{{closure}}
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/98e5df9/internal/compiler/passes/purity_check.rs:20:17
  16: i_slint_compiler::object_tree::recurse_elem_including_sub_components_no_borrow::{{closure}}
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/98e5df9/internal/compiler/object_tree.rs:2171:9
  17: i_slint_compiler::object_tree::recurse_elem_no_borrow
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/98e5df9/internal/compiler/object_tree.rs:2145:17
  18: i_slint_compiler::object_tree::recurse_elem_including_sub_components_no_borrow
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/98e5df9/internal/compiler/object_tree.rs:2158:5
  19: i_slint_compiler::passes::purity_check::purity_check
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/98e5df9/internal/compiler/passes/purity_check.rs:12:9
  20: i_slint_compiler::passes::run_import_passes
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/98e5df9/internal/compiler/passes.rs:294:5
  21: i_slint_compiler::passes::run_passes::{{closure}}
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/98e5df9/internal/compiler/passes.rs:84:5
  22: i_slint_compiler::compile_syntax_node::{{closure}}
             at /home/runner/.cargo/git/checkouts/slint-8153123e5dffa129/98e5df9/internal/compiler/lib.rs:315:76
  23: spin_on::spin_on
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spin_on-0.1.1/src/lib.rs:78:38
  24: slint::check_file
             at ./src/crates/slint/src/main.rs:45:21
  25: slint::main
             at ./src/crates/slint/src/main.rs:25:9
  26: core::ops::function::FnOnce::call_once
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

##### Automatic Fuzzer note, output status "None", output signal "Some(6)"
```

[compressed.zip](https://github.com/user-attachments/files/17983003/compressed.zip)

### Environment Details

- Slint Version: Git
- Platform/OS: Linux

**Comment by ogoffart** [comment]
Thanks for the bug report.
That was an actual bug that in release mode, we wouldn't error out despite calling focus() on an impure function.
